Repository MyOnlineStore/bricks, pull requests merged in 2018-07, with the labels that each got.

#92 Added icon cheatsheets to story
  src/__snapshots__/index.test.ts.snap
  src/components/Icon/assets/desert-large.svg
  src/components/Icon/index.tsx
  src/components/Icon/story.tsx
  src/components/Icon/test.tsx
  src/components/Icon/types.ts
Labels: enhancement 💎

#104 Adds build to prepublish
  package.json
Labels: tooling 🤖

#105 Fixed DontTest stories
  config/jest/__mocks__/simplebar.ts
  config/storybook/config.js
  src/__snapshots__/index.test.ts.snap
  src/components/Modal/index.tsx
  src/components/Modal/story.tsx
  src/components/ScrollBox/story.tsx
  src/components/ScrollBox/test.tsx
  src/index.test.ts
Labels: bugfix 🕶

#113 Buttonvariants
  src/__snapshots__/index.test.ts.snap
  src/components/Button/index.tsx
  src/components/Button/story.tsx
  src/components/Button/style.tsx
  src/components/Button/test.tsx
  src/components/Modal/story.tsx
  src/themes/MosTheme/MosTheme.theme.ts
Labels: enhancement 💎

#115 Updated pr template
  PULL_REQUEST_TEMPLATE.md
Labels: enhancement 💎

#107 Added Illustration and EmptyState components
  .circleci/config.yml
  config/storybook/webpack.config.js
  config/webpack/webpack.config.js
  src/__snapshots__/index.test.ts.snap
  src/components/EmptyState/index.tsx
  src/components/EmptyState/story.tsx
  src/components/Heading/index.tsx
  src/components/Heading/story.tsx
  src/components/Illustration/assets/cactus.color.svg
  src/components/Illustration/index.tsx
  src/components/Illustration/story.tsx
  src/components/Illustration/style.tsx
  src/components/Illustration/types.ts
  src/components/Text/__snapshots__/test.tsx.snap
  src/components/Text/index.tsx
  src/components/Text/story.tsx
  src/components/Text/style.tsx
  src/themes/MosTheme/MosTheme.theme.ts
  src/types/ThemeType.ts
Labels: new addition 👶

#114 Added Select
  config/typescript/tslint.json
  package.json
  src/__snapshots__/index.test.ts.snap
  src/components/Box/__snapshots__/test.tsx.snap
  src/components/Box/index.tsx
  src/components/Box/style.tsx
  src/components/Box/test.tsx
  src/components/Checkbox/index.tsx
  src/components/Checkbox/style.tsx
  src/components/Contrast/index.tsx
  src/components/ErrorBoundary/__snapshots__/test.tsx.snap
  src/components/FoldOut/index.tsx
  src/components/Icon/style.tsx
  src/components/ScrollBox/index.tsx
  src/components/Select/Option/index.tsx
  src/components/Select/Option/style.tsx
  src/components/Select/index.tsx
  src/components/Select/story.tsx
  src/components/Select/style.tsx
  src/components/Select/test.tsx
  src/components/Text/__snapshots__/test.tsx.snap
  src/components/Text/style.tsx
  src/index.ts
  src/themes/MosTheme/MosTheme.theme.ts
  src/types/ThemeType.ts
Labels: new addition 👶

#121 Added InlineNotification component
  .gitignore
  src/index.ts
Labels: new addition 👶

#124 Select window overflow hidden bugs fix
  config/jest/jest.config.json
  package.json
  src/__snapshots__/index.test.ts.snap
  src/components/Select/index.tsx
  src/components/Select/story.tsx
  src/components/Select/style.tsx
  src/components/Select/test.tsx
  src/index.test.ts
  src/themes/MosTheme/MosTheme.theme.ts
Labels: bugfix 🕶

#125 Added fixed width to modal
  src/__snapshots__/index.test.ts.snap
  src/components/Box/style.tsx
  src/components/Modal/__snapshots__/test.tsx.snap
  src/components/Modal/index.tsx
  src/components/Modal/style.tsx
Labels: enhancement 💎

#128 changed default textAlign on Header
  src/__snapshots__/index.test.ts.snap
  src/components/Heading/index.tsx
Labels: enhancement 💎

#129 Replaced all Spacers with Boxes
  src/__snapshots__/index.test.ts.snap
  src/components/BreakpointProvider/index.tsx
  src/components/Button/story.tsx
  src/components/Contrast/story.tsx
  src/components/EmptyState/index.tsx
  src/components/ErrorBoundary/__snapshots__/test.tsx.snap
  src/components/FoldOut/story.tsx
  src/components/Icon/story.tsx
  src/components/MessageStream/index.tsx
  src/components/Modal/index.tsx
  src/components/Notification/index.tsx
  src/components/Popover/story.tsx
  src/components/RadioButton/index.tsx
  src/components/ScrollBox/story.tsx
  src/components/Select/Option/index.tsx
  src/components/Select/index.tsx
  src/components/TextField/index.tsx
  src/components/Toggle/index.tsx
Labels: enhancement 💎

#108 Table
  config/jest/__mocks__/reactBeautifulDnd.tsx
  config/jest/__mocks__/reactIntl.ts
  config/jest/__mocks__/reactPopper.tsx
  config/jest/jest.config.json
  config/typescript/tslint.json
  package-lock.json
  package.json
  src/__snapshots__/index.test.ts.snap
  src/components/Button/index.tsx
  src/components/Button/style.tsx
  src/components/Button/test.tsx
  src/components/Contrast/index.tsx
  src/components/Contrast/style.tsx
  src/components/Table/index.tsx
  src/components/Table/story.tsx
  src/components/Table/style.tsx
  src/components/Table/test.tsx
  src/components/TableCell/index.tsx
  src/components/TableCell/style.tsx
  src/components/TableRow/Row/index.tsx
  src/components/TableRow/index.tsx
  src/components/TableRow/style.tsx
  src/components/TableRow/test.tsx
  src/index.ts
  src/themes/MosTheme/MosTheme.theme.ts
  src/types/ThemeType.ts
Labels: new addition 👶

#126 Font smoothing for Text and Heading, z-index for Modal
  package-lock.json
  src/__snapshots__/index.test.ts.snap
  src/components/Heading/index.tsx
  src/components/Modal/__snapshots__/test.tsx.snap
  src/components/Modal/index.tsx
  src/components/Modal/story.tsx
  src/components/Modal/style.tsx
  src/components/Modal/test.tsx
  src/components/Text/__snapshots__/test.tsx.snap
  src/components/Text/style.tsx
Labels: enhancement 💎
