Repository MyOnlineStore/bricks, pull requests merged in 2018-08, with the labels that each got.

#135 Lowered Modal z-index
  src/__snapshots__/index.test.ts.snap
  src/components/Modal/style.tsx
Labels: bugfix 🕶

#136 Added components to index and changed PR template
  PULL_REQUEST_TEMPLATE.md
  src/index.ts
Labels: enhancement 💎

#133 Added close on click outside to Modal
  src/components/Modal/index.tsx
  src/components/Modal/test.tsx
Labels: enhancement 💎

#141 Added text skeleton
  src/__snapshots__/index.test.ts.snap
  src/components/Popover/__snapshots__/test.tsx.snap
  src/components/Popover/style.tsx
  src/components/Skeleton/Text/index.tsx
  src/components/Skeleton/Text/style.tsx
  src/components/Skeleton/index.tsx
  src/components/Skeleton/story.tsx
  src/components/Skeleton/style.tsx
  src/components/Skeleton/test.tsx
  src/components/Table/story.tsx
  src/index.test.ts
  src/index.ts
  src/themes/MosTheme/MosTheme.theme.ts
  src/types/ThemeType.ts
  src/utility/calculateRandomPercentage/index.ts
  src/utility/calculateRandomPercentage/test.ts
Labels: new addition 👶

#146 Fixed button skeleton height
  src/__snapshots__/index.test.ts.snap
  src/components/Skeleton/Button/style.tsx
  src/components/Skeleton/Text/style.tsx
  src/components/Skeleton/style.tsx
Labels: bugfix 🕶

#147 made Select window invisible when collapsed
  src/__snapshots__/index.test.ts.snap
  src/components/Select/story.tsx
  src/components/Select/style.tsx
Labels: bugfix 🕶

#148 Added production NODE_ENV to webpack config, updated packages
  config/webpack/webpack.config.js
  package-lock.json
Labels: bugfix 🕶

#151 Added modal size prop
  src/__snapshots__/index.test.ts.snap
  src/components/Modal/index.tsx
  src/components/Modal/story.tsx
  src/components/Modal/style.tsx
  src/components/Modal/test.tsx
Labels: enhancement 💎

#152 Added inline-notification children
  src/__snapshots__/index.test.ts.snap
  src/components/InlineNotification/index.tsx
  src/components/InlineNotification/story.tsx
Labels: enhancement 💎

#153 Fixed source-maps
  config/webpack/webpack.config.js
Labels: bugfix 🕶, tooling 🤖

#145 Added headers prop to Table
  .circleci/config.yml
  config/jest/jest.config.json
  package-lock.json
  package.json
  src/__snapshots__/index.test.ts.snap
  src/components/Checkbox/index.tsx
  src/components/Checkbox/story.tsx
  src/components/Checkbox/style.tsx
  src/components/Checkbox/test.tsx
  src/components/RadioButton/index.tsx
  src/components/RadioButton/story.tsx
  src/components/RadioButton/test.tsx
  src/components/RadioButtonGroup/story.tsx
  src/components/Table/Cell/index.tsx
  src/components/Table/Cell/style.tsx
  src/components/Table/Header/index.tsx
  src/components/Table/Header/style.tsx
  src/components/Table/Header/test.tsx
  src/components/Table/Row/index.tsx
  src/components/Table/Row/style.tsx
  src/components/Table/Row/test.tsx
  src/components/Table/index.tsx
  src/components/Table/story.tsx
  src/components/Table/style.tsx
  src/components/Table/test.tsx
  src/components/TableCell/style.tsx
  src/components/TableRow/Row/index.tsx
  src/components/TableRow/index.tsx
  src/components/TableRow/style.tsx
  src/components/TableRow/test.tsx
  src/index.ts
  src/themes/MosTheme/MosTheme.theme.ts
  src/types/ThemeType.ts
  src/utility/Branch/__snapshots__/test.tsx.snap
  src/utility/Branch/index.tsx
  src/utility/Branch/test.tsx
  src/utility/SubscriptionContext/index.tsx
Labels: enhancement 💎

#158 Updated TextField
  src/__snapshots__/index.test.ts.snap
  src/components/TextField/index.tsx
  src/components/TextField/story.tsx
  src/components/TextField/style.tsx
  src/components/TextField/test.tsx
  src/themes/MosTheme/MosTheme.theme.ts
Labels: enhancement 💎

#149 Reduced bundle size
  .circleci/config.yml
  config/jest/jest.config.json
  config/typescript/tslint.json
  config/webpack/webpack.config.js
  package-lock.json
  package.json
  src/components/Button/test.tsx
  src/components/Checkbox/style.tsx
  src/components/Checkbox/test.tsx
  src/components/Icon/test.tsx
  src/components/Link/test.tsx
  src/components/MessageStream/index.tsx
  src/components/MessageStream/test.tsx
  src/components/Modal/test.tsx
  src/components/Popover/test.tsx
  src/components/RadioButton/test.tsx
  src/components/Raised/test.tsx
  src/components/ScrollBox/test.tsx
  src/components/Select/style.tsx
  src/components/Select/test.tsx
  src/components/Skeleton/Text/style.tsx
  src/components/Skeleton/test.tsx
  src/components/Table/Header/test.tsx
  src/components/Table/Row/test.tsx
  src/components/Table/test.tsx
  src/components/Text/test.tsx
  src/components/TextField/test.tsx
  src/components/Toggle/test.tsx
  src/index.ts
  src/utility/styled/index.tsx
  src/utility/styled/testing.tsx
Labels: tooling 🤖

#159 Added Currency formatting to TextField
  config/jest/setup.tsx
  package-lock.json
  package.json
  src/__snapshots__/index.test.ts.snap
  src/components/Badge/__snapshots__/story.storyshot
  src/components/Box/__snapshots__/story.storyshot
  src/components/BreakpointProvider/__snapshots__/story.storyshot
  src/components/Button/__snapshots__/story.storyshot
  src/components/ButtonGroup/__snapshots__/story.storyshot
  src/components/Checkbox/__snapshots__/story.storyshot
  src/components/Contrast/__snapshots__/story.storyshot
  src/components/EmptyState/__snapshots__/story.storyshot
  src/components/ErrorBoundary/__snapshots__/story.storyshot
  src/components/FoldOut/__snapshots__/story.storyshot
  src/components/Heading/__snapshots__/story.storyshot
  src/components/Icon/__snapshots__/story.storyshot
  src/components/Illustration/__snapshots__/story.storyshot
  src/components/InlineNotification/__snapshots__/story.storyshot
  src/components/Link/__snapshots__/story.storyshot
  src/components/MessageStream/__snapshots__/story.storyshot
  src/components/MessageStream/style.tsx
  src/components/Modal/__snapshots__/story.storyshot
  src/components/Notification/__snapshots__/story.storyshot
  src/components/Popover/__snapshots__/story.storyshot
  src/components/Popover/style.tsx
  src/components/PriceTag/__snapshots__/story.storyshot
  src/components/RadioButton/__snapshots__/story.storyshot
  src/components/RadioButtonGroup/__snapshots__/story.storyshot
  src/components/Raised/__snapshots__/story.storyshot
  src/components/ScrollBox/__snapshots__/story.storyshot
  src/components/Select/__snapshots__/story.storyshot
  src/components/Skeleton/__snapshots__/story.storyshot
  src/components/Spacer/__snapshots__/story.storyshot
  src/components/Table/__snapshots__/story.storyshot
  src/components/Text/__snapshots__/story.storyshot
  src/components/TextField/formatters/withCurrencyFormatting/__snapshots__/story.storyshot
  src/components/TextField/formatters/withCurrencyFormatting/index.tsx
  src/components/TextField/formatters/withCurrencyFormatting/story.tsx
  src/components/TextField/formatters/withCurrencyFormatting/test.tsx
  src/components/TextField/index.tsx
  src/components/TextField/style.tsx
  src/components/Tile/__snapshots__/story.storyshot
  src/components/Toggle/__snapshots__/story.storyshot
  src/components/TransitionAnimation/__snapshots__/story.storyshot
  src/index.test.ts
  src/themes/MosTheme/MosTheme.theme.ts
Labels: enhancement 💎

#156 create FormRow component
  config/typescript/tslint.json
  src/components/Button/__snapshots__/story.storyshot
  src/components/Button/index.tsx
  src/components/ButtonGroup/__snapshots__/story.storyshot
  src/components/Contrast/__snapshots__/story.storyshot
  src/components/EmptyState/__snapshots__/story.storyshot
  src/components/FoldOut/__snapshots__/story.storyshot
  src/components/FormRow/__snapshots__/story.storyshot
  src/components/FormRow/index.tsx
  src/components/FormRow/story.tsx
  src/components/InlineNotification/__snapshots__/story.storyshot
  src/components/Link/__snapshots__/story.storyshot
  src/components/MessageStream/__snapshots__/story.storyshot
  src/components/Modal/__snapshots__/story.storyshot
  src/components/Popover/__snapshots__/story.storyshot
  src/components/PriceTag/__snapshots__/story.storyshot
  src/components/RadioButton/__snapshots__/story.storyshot
  src/components/RadioButton/style.tsx
  src/components/RadioButtonGroup/__snapshots__/story.storyshot
  src/components/RadioButtonGroup/index.tsx
  src/components/Raised/__snapshots__/story.storyshot
  src/components/ScrollBox/__snapshots__/story.storyshot
  src/components/Select/__snapshots__/story.storyshot
  src/components/Skeleton/__snapshots__/story.storyshot
  src/components/Spacer/__snapshots__/story.storyshot
  src/components/Table/__snapshots__/story.storyshot
  src/components/TextField/formatters/withCurrencyFormatting/__snapshots__/story.storyshot
  src/components/TextField/style.tsx
  src/components/TransitionAnimation/__snapshots__/story.storyshot
  src/index.ts
  src/themes/MosTheme/MosTheme.theme.ts
Labels: new addition 👶

#150 Toaster Component
  src/components/Spacer/__snapshots__/story.storyshot
  src/components/Toaster/__snapshots__/story.storyshot
  src/components/Toaster/index.tsx
  src/components/Toaster/story.tsx
  src/components/Toaster/style.tsx
  src/components/Toaster/test.tsx
  src/components/Toggle/__snapshots__/story.storyshot
  src/components/TransitionAnimation/__snapshots__/story.storyshot
  src/index.ts
  src/themes/MosTheme/MosTheme.theme.ts
  src/types/ThemeType.ts
Labels: new addition 👶

#168 Removed unnecessary horizontal scrollbar in Scrollbox
  src/components/Modal/__snapshots__/story.storyshot
  src/components/ScrollBox/__snapshots__/story.storyshot
  src/components/ScrollBox/style.tsx
  src/components/Select/__snapshots__/story.storyshot
Labels: bugfix 🕶
