Repository MyOnlineStore/bricks, pull requests merged in 2018-06, with the labels that each got.

#71 Added new bell icon
  src/components/Icon/Icon.types.ts
  src/components/Icon/assets/bell-slash.svg
  src/components/Icon/assets/bell.svg
Labels: enhancement 💎

#73 Added missing exports
  src/index.ts
Labels: bugfix 🕶

#74 Added offset prop to Popover
  config/jest/__mocks__/reactIntl.ts
  config/jest/__mocks__/reactPopper.tsx
  config/jest/jest.config.json
  config/jest/setup.tsx
  src/__snapshots__/index.test.ts.snap
  src/components/Popover/__snapshots__/test.tsx.snap
  src/components/Popover/index.tsx
  src/components/Popover/story.tsx
  src/components/Popover/style.tsx
  src/components/Popover/test.tsx
  src/types/ThemeType.ts
Labels: enhancement 💎

#80 Added Intrinsic attributes to Spacer and Box
  src/components/Box/index.tsx
  src/components/Box/story.tsx
  src/components/Box/style.tsx
  src/components/Box/test.tsx
  src/components/BreakpointProvider/index.tsx
  src/components/BreakpointProvider/test.tsx
  src/components/Button/index.tsx
  src/components/Button/story.tsx
  src/components/Button/style.tsx
  src/components/Button/test.tsx
  src/components/ButtonGroup/index.tsx
  src/components/ButtonGroup/test.tsx
  src/components/Contrast/index.tsx
  src/components/ErrorBoundary/index.tsx
  src/components/ErrorBoundary/test.tsx
  src/components/FoldOut/index.tsx
  src/components/FoldOut/test.tsx
  src/components/Heading/index.tsx
  src/components/Heading/story.tsx
  src/components/Icon/index.tsx
  src/components/Icon/story.tsx
  src/components/Icon/style.tsx
  src/components/InlineNotification/story.tsx
  src/components/MessageStream/index.tsx
  src/components/MessageStream/story.tsx
  src/components/MessageStream/style.tsx
  src/components/MessageStream/test.tsx
  src/components/Notification/index.tsx
  src/components/Notification/story.tsx
  src/components/Notification/style.tsx
  src/components/PriceTag/index.tsx
  src/components/PriceTag/story.tsx
  src/components/PriceTag/style.tsx
  src/components/ScrollBox/__snapshots__/test.tsx.snap
  src/components/ScrollBox/index.tsx
  src/components/ScrollBox/story.DontTest.tsx
  src/components/ScrollBox/style.tsx
  src/components/ScrollBox/test.tsx
  src/components/Spacer/index.tsx
  src/components/Spacer/style.tsx
  src/components/SubHeading/index.tsx
  src/components/SubHeading/story.tsx
  src/components/Text/index.tsx
  src/components/Text/story.tsx
  src/components/Text/style.tsx
  src/components/Text/test.tsx
  src/components/TextField/test.tsx
  src/components/TransitionAnimation/index.tsx
  src/components/TransitionAnimation/test.tsx
  src/themes/MerchantTheme/MerchantTheme.test.tsx
  src/utility/styled/index.tsx
Labels: enhancement 💎

#79 created Link component
  src/__snapshots__/index.test.ts.snap
  src/components/ButtonGroup/index.tsx
  src/components/ButtonGroup/test.tsx
  src/components/FoldOut/index.tsx
  src/components/Link/index.tsx
  src/components/Link/story.tsx
  src/components/Link/style.tsx
  src/components/Link/test.tsx
  src/components/MessageStream/index.tsx
  src/components/ScrollBox/test.tsx
  src/index.ts
  src/themes/MosTheme/MosTheme.theme.ts
  src/types/ThemeType.ts
Labels: new addition 👶

#78 Radiobutton
  src/__snapshots__/index.test.ts.snap
  src/components/RadioButton/index.tsx
  src/components/RadioButton/story.tsx
  src/components/RadioButton/style.tsx
  src/components/RadioButton/test.tsx
  src/components/RadioButtonGroup/index.tsx
  src/components/RadioButtonGroup/story.tsx
  src/index.ts
  src/themes/MosTheme/MosTheme.theme.ts
  src/types/ThemeType.ts
Labels: new addition 👶

#87 Added 18 to PxCoordinateType
  src/utility/trbl/index.ts
Labels: enhancement 💎

#89 Added compact styling to Text
  src/components/Text/index.tsx
  src/components/Text/story.tsx
  src/components/Text/style.tsx
  src/components/Text/test.tsx
Labels: enhancement 💎

#90 Added Icon types and ThemeType exports
  src/index.ts
Labels: enhancement 💎

#88 Popoverfixes
  src/__snapshots__/index.test.ts.snap
  src/components/Popover/__snapshots__/test.tsx.snap
  src/components/Popover/index.tsx
  src/components/Popover/story.tsx
  src/components/Popover/style.tsx
  src/components/Popover/test.tsx
Labels: enhancement 💎

#91 Added transparent background color to Link hover state
  src/__snapshots__/index.test.ts.snap
  src/components/Link/style.tsx
Labels: enhancement 💎
