Repository MyOnlineStore/bricks, pull requests merged in 2018-09, with the labels that each got.

#185 SSR compatibility
  config/jest/__mocks__/cssMock.js
  config/jest/__mocks__/simplebarCss.ts
  config/jest/jest.config.json
  config/storybook/webpack.config.js
  config/typescript/tsconfig.json
  config/webpack/webpack.config.js
  package-lock.json
  package.json
  src/components/Modal/__snapshots__/story.storyshot
  src/components/MultiButton/__snapshots__/story.storyshot
  src/components/Popover/__snapshots__/story.storyshot
  src/components/PriceTag/__snapshots__/story.storyshot
  src/components/RadioButtonGroup/__snapshots__/story.storyshot
  src/components/Raised/__snapshots__/story.storyshot
  src/components/ScrollBox/__snapshots__/story.storyshot
  src/components/ScrollBox/index.tsx
  src/components/ScrollBox/style.tsx
  src/components/Select/__snapshots__/story.storyshot
  src/components/Skeleton/__snapshots__/story.storyshot
  src/components/Spacer/__snapshots__/story.storyshot
  src/components/Table/__snapshots__/story.storyshot
  src/components/Tile/__snapshots__/story.storyshot
  src/components/Toaster/__snapshots__/story.storyshot
  src/components/Toggle/__snapshots__/story.storyshot
  src/components/TransitionAnimation/__snapshots__/story.storyshot
Labels: bugfix 🕶

#189 Removed close button without closeAction
  src/components/Modal/__snapshots__/story.storyshot
  src/components/Modal/index.tsx
  src/components/Modal/story.tsx
  src/components/Modal/test.tsx
Labels: bugfix 🕶

#187 added disabled state to Select Component
  src/components/Select/__snapshots__/story.storyshot
  src/components/Select/index.tsx
  src/components/Select/story.tsx
  src/components/Select/style.tsx
  src/components/Select/test.tsx
  src/components/Skeleton/__snapshots__/story.storyshot
  src/components/Spacer/__snapshots__/story.storyshot
  src/components/Table/__snapshots__/story.storyshot
  src/components/Tile/__snapshots__/story.storyshot
  src/components/Toaster/__snapshots__/story.storyshot
  src/components/Toggle/__snapshots__/story.storyshot
  src/components/TransitionAnimation/__snapshots__/story.storyshot
  src/themes/MosTheme/MosTheme.theme.ts
Labels: enhancement 💎

#183 Added bulk actions to Table
  config/jest/setup.tsx
  src/components/Checkbox/__snapshots__/story.storyshot
  src/components/Checkbox/index.tsx
  src/components/Checkbox/test.tsx
  src/components/Table/Header/test.tsx
  src/components/Table/Row/index.tsx
  src/components/Table/Row/test.tsx
  src/components/Table/__snapshots__/story.storyshot
  src/components/Table/index.tsx
  src/components/Table/story.tsx
  src/components/Table/test.tsx
  src/declarations/global.d.ts
  src/utility/SubscriptionContext/index.tsx
Labels: enhancement 💎

#194 All select options are now clickable + added key shortcuts
  src/components/Select/index.tsx
  src/components/Select/test.tsx
Labels: bugfix 🕶, enhancement 💎

#193 FormRow widths and margins adjusted
  src/components/Box/__snapshots__/story.storyshot
  src/components/BreakpointProvider/__snapshots__/story.storyshot
  src/components/Checkbox/__snapshots__/story.storyshot
  src/components/Checkbox/style.tsx
  src/components/EmptyState/__snapshots__/story.storyshot
  src/components/ErrorBoundary/__snapshots__/story.storyshot
  src/components/FoldOut/__snapshots__/story.storyshot
  src/components/FormRow/__snapshots__/story.storyshot
  src/components/FormRow/index.tsx
  src/components/FormRow/story.tsx
  src/components/InlineNotification/__snapshots__/story.storyshot
  src/components/Link/__snapshots__/story.storyshot
  src/components/MessageStream/__snapshots__/story.storyshot
  src/components/Modal/__snapshots__/story.storyshot
  src/components/MultiButton/__snapshots__/story.storyshot
  src/components/Popover/__snapshots__/story.storyshot
  src/components/PriceTag/__snapshots__/story.storyshot
  src/components/RadioButton/__snapshots__/story.storyshot
  src/components/RadioButtonGroup/__snapshots__/story.storyshot
  src/components/RadioButtonGroup/index.tsx
  src/components/Raised/__snapshots__/story.storyshot
  src/components/ScrollBox/__snapshots__/story.storyshot
  src/components/Select/__snapshots__/story.storyshot
  src/components/Skeleton/__snapshots__/story.storyshot
  src/components/Spacer/__snapshots__/story.storyshot
  src/components/Table/__snapshots__/story.storyshot
  src/components/Text/__snapshots__/story.storyshot
  src/components/Text/__snapshots__/test.tsx.snap
  src/components/Text/style.tsx
  src/components/TextField/formatters/withCurrencyFormatting/__snapshots__/story.storyshot
  src/components/Tile/__snapshots__/story.storyshot
  src/components/Toaster/__snapshots__/story.storyshot
  src/components/Toggle/__snapshots__/story.storyshot
  src/components/Toggle/index.tsx
  src/components/Toggle/style.tsx
  src/components/TransitionAnimation/__snapshots__/story.storyshot
Labels: bugfix 🕶

#201 Added alternative input rendering option to Select
  src/components/Modal/__snapshots__/story.storyshot
  src/components/ScrollBox/__snapshots__/story.storyshot
  src/components/ScrollBox/style.tsx
  src/components/Select/__snapshots__/story.storyshot
  src/components/Select/index.tsx
  src/components/Select/story.tsx
  src/components/Select/style.tsx
  src/components/Select/test.tsx
Labels: enhancement 💎

#199 Solved currency input bugs
  src/components/FormRow/__snapshots__/story.storyshot
  src/components/TextField/formatters/withCurrencyFormatting/__snapshots__/story.storyshot
  src/components/TextField/formatters/withCurrencyFormatting/index.tsx
  src/components/TextField/formatters/withCurrencyFormatting/story.tsx
  src/components/TextField/formatters/withCurrencyFormatting/test.tsx
  src/components/TextField/index.tsx
  src/components/TextField/story.tsx
  src/components/TextField/style.tsx
  src/components/TextField/test.tsx
  src/themes/MosTheme/MosTheme.theme.ts
Labels: bugfix 🕶

#208 Added branch component
  src/components/Branch/__snapshots__/story.storyshot
  src/components/Branch/__snapshots__/test.tsx.snap
  src/components/Branch/index.tsx
  src/components/Branch/story.tsx
  src/components/Branch/test.tsx
  src/components/Table/Row/index.tsx
  src/components/Table/index.tsx
  src/index.ts
Labels: new addition 👶

#209 Added name attribute to inputfield and removed unused active prop
  src/components/FormRow/__snapshots__/story.storyshot
  src/components/TextField/formatters/withCurrencyFormatting/__snapshots__/story.storyshot
  src/components/TextField/index.tsx
  src/components/TextField/style.tsx
  src/components/TextField/test.tsx
  src/themes/MosTheme/MosTheme.theme.ts
Labels: breaking 🔥, enhancement 💎
