Repository MyOnlineStore/bricks, pull requests merged in 2018-10, with the labels that each got.

#211 Added z-index to Scrollbox shadows
  src/components/Modal/__snapshots__/story.storyshot
  src/components/ScrollBox/__snapshots__/story.storyshot
  src/components/ScrollBox/style.tsx
Labels: bugfix 🕶

#207 Added Range Component
  config/jest/__mocks__/reactInputRange.tsx
  config/jest/jest.config.json
  package-lock.json
  package.json
  src/components/Checkbox/index.tsx
  src/components/FormRow/__snapshots__/story.storyshot
  src/components/Range/__snapshots__/story.storyshot
  src/components/Range/index.tsx
  src/components/Range/story.tsx
  src/components/Range/style.tsx
  src/components/Range/test.tsx
  src/components/ScrollBox/__snapshots__/story.storyshot
  src/components/Select/__snapshots__/story.storyshot
  src/components/Skeleton/__snapshots__/story.storyshot
  src/components/Spacer/__snapshots__/story.storyshot
  src/components/Table/__snapshots__/story.storyshot
  src/components/TextField/formatters/withCurrencyFormatting/__snapshots__/story.storyshot
  src/components/TextField/formatters/withCurrencyFormatting/index.tsx
  src/components/TextField/formatters/withNumberFormatting/index.tsx
  src/components/TextField/formatters/withNumberFormatting/story.tsx
  src/components/TextField/formatters/withNumberFormatting/test.tsx
  src/components/TextField/index.tsx
  src/components/TextField/style.tsx
  src/components/Tile/__snapshots__/story.storyshot
  src/components/Toaster/__snapshots__/story.storyshot
  src/components/TransitionAnimation/__snapshots__/story.storyshot
  src/index.ts
  src/themes/MosTheme/MosTheme.theme.ts
  src/types/ThemeType.ts
Labels: work in progress ⚔

#216 replaced StatelessComponent identifiers with SFC
  src/components/Box/index.tsx
  src/components/ButtonGroup/index.tsx
  src/components/Contrast/index.tsx
  src/components/EmptyState/index.tsx
  src/components/Heading/index.tsx
  src/components/Icon/index.tsx
  src/components/Illustration/index.tsx
  src/components/Link/index.tsx
  src/components/MessageStream/index.tsx
  src/components/Notification/index.tsx
  src/components/Popover/index.tsx
  src/components/PriceTag/index.tsx
  src/components/Raised/index.tsx
  src/components/Spacer/index.tsx
  src/components/Text/index.tsx
  src/components/TransitionAnimation/index.tsx
Labels: enhancement 💎

#219 Fixed range padding
  src/components/Range/__snapshots__/story.storyshot
  src/components/Range/index.tsx
Labels: bugfix 🕶

#223 Fixed Modal height/fixed button row issues
  src/components/Modal/__snapshots__/story.storyshot
  src/components/Modal/style.tsx
  src/components/ScrollBox/__snapshots__/story.storyshot
  src/components/ScrollBox/style.tsx
  src/components/Select/__snapshots__/story.storyshot
Labels: bugfix 🕶

#198 Added eventlisteners to Popover for optional internal state management
  config/jest/setup.tsx
  src/components/Popover/__snapshots__/story.storyshot
  src/components/Popover/__snapshots__/test.tsx.snap
  src/components/Popover/index.tsx
  src/components/Popover/story.tsx
  src/components/Popover/test.tsx
  src/index.test.ts
Labels: enhancement 💎

#214 Inputfield - improved focus and feedback
  src/components/FormRow/__snapshots__/story.storyshot
  src/components/Range/__snapshots__/story.storyshot
  src/components/TextField/formatters/withCurrencyFormatting/__snapshots__/story.storyshot
  src/components/TextField/index.tsx
  src/components/TextField/style.tsx
  src/themes/MosTheme/MosTheme.theme.ts
Labels: enhancement 💎

#226 Test coverage - 100%
  src/components/Button/__snapshots__/story.storyshot
  src/components/Button/style.tsx
  src/components/ButtonGroup/__snapshots__/story.storyshot
  src/components/Contrast/__snapshots__/story.storyshot
  src/components/EmptyState/__snapshots__/story.storyshot
  src/components/FoldOut/__snapshots__/story.storyshot
  src/components/MessageStream/__snapshots__/story.storyshot
  src/components/Modal/__snapshots__/story.storyshot
  src/components/MultiButton/__snapshots__/story.storyshot
  src/components/Popover/__snapshots__/story.storyshot
  src/components/Popover/index.tsx
  src/components/Popover/test.tsx
  src/components/Select/Option/__snapshots__/test.tsx.snap
  src/components/Select/Option/index.tsx
  src/components/Select/Option/test.tsx
  src/components/Select/__snapshots__/story.storyshot
  src/components/Select/style.tsx
  src/components/Select/test.tsx
  src/components/Table/__snapshots__/story.storyshot
  src/components/Toaster/__snapshots__/story.storyshot
Labels: bugfix 🕶

#221 Added severity prop to the badge component
  config/typescript/tslint.json
  src/components/Badge/__snapshots__/story.storyshot
  src/components/Badge/index.tsx
  src/components/Badge/story.tsx
  src/components/MultiButton/story.tsx
  src/components/Select/__snapshots__/story.storyshot
  src/components/Select/style.tsx
  src/themes/MosTheme/MosTheme.theme.ts
Labels: enhancement 💎

#212 Table check
  src/components/Checkbox/index.tsx
  src/components/Table/Header/index.tsx
  src/components/Table/Header/test.tsx
  src/components/Table/Row/index.tsx
  src/components/Table/Row/test.tsx
  src/components/Table/index.tsx
  src/components/Table/story.tsx
  src/components/Table/test.tsx
Labels: enhancement 💎

#225 Slide in animation
  src/components/Button/__snapshots__/story.storyshot
  src/components/Button/style.tsx
  src/components/ButtonGroup/__snapshots__/story.storyshot
  src/components/Contrast/__snapshots__/story.storyshot
  src/components/EmptyState/__snapshots__/story.storyshot
  src/components/FoldOut/__snapshots__/story.storyshot
  src/components/MessageStream/__snapshots__/story.storyshot
  src/components/Modal/__snapshots__/story.storyshot
  src/components/MultiButton/__snapshots__/story.storyshot
  src/components/Popover/__snapshots__/story.storyshot
  src/components/Select/__snapshots__/story.storyshot
  src/components/Table/__snapshots__/story.storyshot
  src/components/Toaster/__snapshots__/story.storyshot
  src/components/TransitionAnimation/__snapshots__/story.storyshot
  src/components/TransitionAnimation/__snapshots__/test.tsx.snap
  src/components/TransitionAnimation/animations/slideDown.ts
  src/components/TransitionAnimation/animations/slideLeft.ts
  src/components/TransitionAnimation/animations/slideRight.ts
  src/components/TransitionAnimation/animations/slideUp.ts
  src/components/TransitionAnimation/story.tsx
  src/components/TransitionAnimation/style.tsx
  src/components/TransitionAnimation/test.tsx
Labels: new addition 👶

#220 Button refactor
  config/typescript/tslint.json
  src/components/Button/BareButton/index.tsx
  src/components/Button/BareButton/style.tsx
  src/components/Button/__snapshots__/story.storyshot
  src/components/Button/index.tsx
  src/components/Button/story.tsx
  src/components/Button/style.tsx
  src/components/Button/styleCta.tsx
  src/components/Button/styleDefault.tsx
  src/components/Button/styleFlat.tsx
  src/components/Button/test.tsx
  src/components/ButtonGroup/__snapshots__/story.storyshot
  src/components/Checkbox/__snapshots__/story.storyshot
  src/components/Contrast/__snapshots__/story.storyshot
  src/components/EmptyState/__snapshots__/story.storyshot
  src/components/FoldOut/__snapshots__/story.storyshot
  src/components/FoldOut/story.tsx
  src/components/FormRow/__snapshots__/story.storyshot
  src/components/Heading/__snapshots__/story.storyshot
  src/components/InlineNotification/__snapshots__/story.storyshot
  src/components/Link/__snapshots__/story.storyshot
  src/components/Link/index.tsx
  src/components/Link/story.tsx
  src/components/Link/test.tsx
  src/components/MessageStream/__snapshots__/story.storyshot
  src/components/MessageStream/index.tsx
  src/components/MessageStream/story.tsx
  src/components/MessageStream/test.tsx
  src/components/Modal/__snapshots__/story.storyshot
  src/components/Modal/index.tsx
  src/components/Modal/test.tsx
  src/components/MultiButton/__snapshots__/story.storyshot
  src/components/MultiButton/index.tsx
  src/components/MultiButton/story.tsx
  src/components/MultiButton/test.tsx
  src/components/Notification/__snapshots__/story.storyshot
  src/components/Popover/__snapshots__/story.storyshot
  src/components/Popover/story.tsx
  src/components/PriceTag/__snapshots__/story.storyshot
  src/components/RadioButton/__snapshots__/story.storyshot
  src/components/RadioButtonGroup/__snapshots__/story.storyshot
  src/components/Raised/__snapshots__/story.storyshot
  src/components/Range/__snapshots__/story.storyshot
  src/components/ScrollBox/__snapshots__/story.storyshot
  src/components/Select/__snapshots__/story.storyshot
  src/components/Select/index.tsx
  src/components/Select/style.tsx
  src/components/Skeleton/__snapshots__/story.storyshot
  src/components/Spacer/__snapshots__/story.storyshot
  src/components/Table/__snapshots__/story.storyshot
  src/components/Table/story.tsx
  src/components/TextField/formatters/withCurrencyFormatting/__snapshots__/story.storyshot
  src/components/Tile/__snapshots__/story.storyshot
  src/components/Toaster/__snapshots__/story.storyshot
  src/components/Toaster/index.tsx
  src/components/Toaster/story.tsx
  src/components/Toaster/test.tsx
  src/components/Toggle/__snapshots__/story.storyshot
  src/components/TransitionAnimation/__snapshots__/story.storyshot
  src/themes/MosTheme/MosTheme.theme.ts
Labels: breaking 🔥, enhancement 💎

#224 Added TextArea component
  src/components/Spacer/__snapshots__/story.storyshot
  src/components/TextArea/__snapshots__/story.storyshot
  src/components/TextArea/index.tsx
  src/components/TextArea/story.tsx
  src/components/TextArea/style.tsx
  src/components/TextArea/test.tsx
  src/components/TextField/index.tsx
  src/components/TextField/style.tsx
  src/components/TextField/test.tsx
  src/components/Tile/__snapshots__/story.storyshot
  src/components/Toaster/__snapshots__/story.storyshot
  src/components/TransitionAnimation/__snapshots__/story.storyshot
  src/index.ts
  src/themes/MosTheme/MosTheme.theme.ts
  src/types/ThemeType.ts
Labels: new addition 👶

#228 refactored the Text Component to the size-steps according to design
  src/components/Badge/index.tsx
  src/components/Box/__snapshots__/story.storyshot
  src/components/Branch/__snapshots__/story.storyshot
  src/components/BreakpointProvider/__snapshots__/story.storyshot
  src/components/EmptyState/__snapshots__/story.storyshot
  src/components/EmptyState/index.tsx
  src/components/ErrorBoundary/__snapshots__/story.storyshot
  src/components/FoldOut/__snapshots__/story.storyshot
  src/components/FormRow/__snapshots__/story.storyshot
  src/components/FormRow/story.tsx
  src/components/InlineNotification/__snapshots__/story.storyshot
  src/components/Link/__snapshots__/story.storyshot
  src/components/MessageStream/__snapshots__/story.storyshot
  src/components/MessageStream/index.tsx
  src/components/Modal/__snapshots__/story.storyshot
  src/components/MultiButton/index.tsx
  src/components/RadioButton/__snapshots__/story.storyshot
  src/components/RadioButtonGroup/__snapshots__/story.storyshot
  src/components/ScrollBox/__snapshots__/story.storyshot
  src/components/Select/Option/index.tsx
  src/components/Select/__snapshots__/story.storyshot
  src/components/Select/index.tsx
  src/components/Select/story.tsx
  src/components/Spacer/__snapshots__/story.storyshot
  src/components/Table/Row/index.tsx
  src/components/Table/__snapshots__/story.storyshot
  src/components/Text/__snapshots__/story.storyshot
  src/components/Text/__snapshots__/test.tsx.snap
  src/components/Text/index.tsx
  src/components/Text/story.tsx
  src/components/Text/style.tsx
  src/components/Text/test.tsx
  src/components/TextField/formatters/withCurrencyFormatting/__snapshots__/story.storyshot
  src/components/TextField/style.tsx
  src/components/Toaster/__snapshots__/story.storyshot
  src/components/Toaster/style.tsx
  src/components/Toggle/__snapshots__/story.storyshot
  src/components/Toggle/index.tsx
  src/themes/MosTheme/MosTheme.theme.ts
Labels: breaking 🔥, enhancement 💎

#229 refactored the Heading Component to the size-steps according to design
  src/components/EmptyState/__snapshots__/story.storyshot
  src/components/Heading/__snapshots__/story.storyshot
  src/components/Heading/__snapshots__/test.tsx.snap
  src/components/Heading/index.tsx
  src/components/Heading/story.tsx
  src/components/Heading/test.tsx
  src/components/Modal/__snapshots__/story.storyshot
  src/components/Raised/__snapshots__/story.storyshot
  src/components/ScrollBox/__snapshots__/story.storyshot
  src/components/Select/style.tsx
  src/components/Tile/__snapshots__/story.storyshot
  src/components/TransitionAnimation/__snapshots__/story.storyshot
  src/themes/MerchantTheme/MerchantTheme.test.tsx
  src/themes/MerchantTheme/__snapshots__/MerchantTheme.test.tsx.snap
  src/themes/MosTheme/MosTheme.theme.ts
Labels: enhancement 💎

#239 changed order of Textfield stories and removed focus on disabled bug
  src/components/FormRow/__snapshots__/story.storyshot
  src/components/Range/__snapshots__/story.storyshot
  src/components/TextArea/__snapshots__/story.storyshot
  src/components/TextField/__snapshots__/story.storyshot
  src/components/TextField/formatters/withCurrencyFormatting/story.tsx
  src/components/TextField/formatters/withNumberFormatting/story.tsx
  src/components/TextField/story.tsx
  src/components/TextField/style.tsx
Labels: bugfix 🕶

#234 modal now only too large in IE11
  src/components/Modal/__snapshots__/story.storyshot
  src/components/Modal/style.tsx
Labels: bugfix 🕶

#238 Skeleton button removal
  src/components/Skeleton/Button/index.tsx
  src/components/Skeleton/Button/style.tsx
  src/components/Skeleton/__snapshots__/story.storyshot
  src/components/Skeleton/index.tsx
  src/components/Skeleton/story.tsx
  src/components/Skeleton/style.tsx
  src/components/Skeleton/test.tsx
  src/components/Spacer/__snapshots__/story.storyshot
  src/components/Table/__snapshots__/story.storyshot
  src/components/Tile/__snapshots__/story.storyshot
  src/components/Toaster/__snapshots__/story.storyshot
  src/components/TransitionAnimation/__snapshots__/story.storyshot
  src/themes/MosTheme/MosTheme.theme.ts
Labels: breaking 🔥
