Repository MyOnlineStore/bricks, pull requests merged in 2018-05, with the labels that each got.

#49 Added trbl utility
  PULL_REQUEST_TEMPLATE.md
  config/jest/jest.config.json
  src/__snapshots__/index.test.ts.snap
  src/components/FoldOut/FoldOut.story.tsx
  src/components/Icon/Icon.story.tsx
  src/components/Notification/Notification.template.tsx
  src/components/Spacer/Spacer.story.tsx
  src/components/Spacer/Spacer.style.tsx
  src/components/Spacer/Spacer.template.tsx
  src/index.ts
  src/utility/trbl/index.ts
  src/utility/trbl/trbl.test.ts
Labels: new addition 👶, work in progress ⚔

#46 Added Box component
  package-lock.json
  package.json
  src/__snapshots__/index.test.ts.snap
  src/components/Box/Box.story.tsx
  src/components/Box/Box.style.tsx
  src/components/Box/Box.template.tsx
  src/components/Box/Box.test.tsx
  src/components/Box/__snapshots__/Box.test.tsx.snap
  src/components/Box/index.ts
  src/components/BreakpointProvider/BreakpointProvider.story.tsx
  src/components/ErrorBoundary/ErrorBoundary.story.tsx
  src/components/FlatButton/FlatButton.story.tsx
  src/components/Heading/Heading.story.tsx
  src/components/PriceTag/PriceTag.story.tsx
  src/components/SubHeading/SubHeading.story.tsx
  src/components/Text/Text.story.tsx
  src/index.ts
Labels: new addition 👶

#51 Fixed Box story knob options
  src/components/Box/Box.story.tsx
Labels: bugfix 🕶

#40 Added Nested types to theme
  src/__snapshots__/index.test.ts.snap
  src/components/Button/Button.style.tsx
  src/components/Button/index.ts
  src/components/ErrorBoundary/__snapshots__/ErrorBoundary.test.tsx.snap
  src/components/FlatButton/FlatButton.style.tsx
  src/components/FlatButton/index.ts
  src/components/Heading/Heading.story.tsx
  src/components/Heading/Heading.style.tsx
  src/components/Heading/index.ts
  src/components/Icon/Icon.template.tsx
  src/components/Notification/Notification.style.tsx
  src/components/Notification/index.ts
  src/components/PriceTag/PriceTag.style.tsx
  src/components/PriceTag/__snapshots__/PriceTag.test.tsx.snap
  src/components/PriceTag/index.ts
  src/components/Spacer/Spacer.style.tsx
  src/components/SubHeading/SubHeading.style.tsx
  src/components/SubHeading/index.ts
  src/components/Text/Text.style.tsx
  src/components/Text/index.ts
  src/themes/MerchantTheme/MerchantTheme.template.tsx
  src/themes/MerchantTheme/MerchantTheme.test.tsx
  src/themes/MerchantTheme/__snapshots__/MerchantTheme.test.tsx.snap
  src/themes/MosTheme/MosTheme.theme.ts
  src/themes/MosTheme/index.ts
  src/themes/types/ButtonThemeType.ts
  src/themes/types/FlatButtonThemeType.ts
  src/themes/types/NotificationThemeType.ts
  src/themes/types/ThemeType.ts
  src/types/ThemeType.ts
  src/utility/styled/index.ts
Labels: enhancement 💎

#54 Added displayType prop to PriceTag
  src/__snapshots__/index.test.ts.snap
  src/components/PriceTag/PriceTag.story.tsx
  src/components/PriceTag/PriceTag.style.tsx
  src/components/PriceTag/PriceTag.template.tsx
  src/components/PriceTag/PriceTag.test.tsx
  src/components/PriceTag/__snapshots__/PriceTag.test.tsx.snap
  src/themes/MosTheme/MosTheme.theme.ts
Labels: enhancement 💎

#53 Added ButtonGroup
  .codeclimate.yml
  src/__snapshots__/index.test.ts.snap
  src/components/ButtonGroup/ButtonGroup.story.tsx
  src/components/ButtonGroup/ButtonGroup.template.tsx
  src/components/ButtonGroup/ButtonGroup.test.tsx
  src/components/ButtonGroup/__snapshots__/ButtonGroup.test.tsx.snap
  src/components/ButtonGroup/index.ts
Labels: new addition 👶

#63 Message component
  package-lock.json
  package.json
  src/__snapshots__/index.test.ts.snap
  src/components/MessageStream/MessageStream.story.tsx
  src/components/MessageStream/MessageStream.style.tsx
  src/components/MessageStream/MessageStream.template.tsx
  src/components/MessageStream/MessageStream.test.tsx
  src/components/MessageStream/index.ts
  src/components/Text/Text.test.tsx
  src/themes/MosTheme/MosTheme.theme.ts
  src/types/ThemeType.ts
  src/utility/styled/index.ts
  src/utility/styled/index.tsx
  src/utility/styled/shallowWithTheme.tsx
Labels: new addition 👶

#64 Update circle config
  .circleci/config.yml
Labels: tooling 🤖

#62 Updated button theme and added flat variant
  package-lock.json
  package.json
  src/__snapshots__/index.test.ts.snap
  src/components/Box/Box.style.tsx
  src/components/Button/Button.story.tsx
  src/components/Button/Button.style.tsx
  src/components/Button/Button.template.tsx
  src/components/Button/Button.test.tsx
  src/components/ButtonGroup/ButtonGroup.story.tsx
  src/components/ButtonGroup/ButtonGroup.template.tsx
  src/components/ButtonGroup/ButtonGroup.test.tsx
  src/components/ButtonGroup/__snapshots__/ButtonGroup.test.tsx.snap
  src/components/Contrast/Contrast.story.tsx
  src/components/Contrast/Contrast.style.tsx
  src/components/Contrast/Contrast.template.tsx
  src/components/Contrast/index.ts
  src/components/FlatButton/FlatButton.story.tsx
  src/components/FlatButton/FlatButton.style.tsx
  src/components/FlatButton/FlatButton.template.tsx
  src/components/FlatButton/FlatButton.test.tsx
  src/components/FlatButton/index.ts
  src/components/Heading/Heading.style.tsx
  src/components/Icon/Icon.style.tsx
  src/components/MessageStream/MessageStream.style.tsx
  src/components/MessageStream/MessageStream.template.tsx
  src/components/Notification/Notification.style.tsx
  src/components/PriceTag/PriceTag.style.tsx
  src/components/ScrollBox/ScrollBox.style.tsx
  src/components/Spacer/Spacer.style.tsx
  src/components/SubHeading/SubHeading.style.tsx
  src/components/Text/Text.style.tsx
  src/index.ts
  src/themes/MosTheme/MosTheme.theme.ts
  src/types/RecursivePartial.ts
  src/types/ThemeType.ts
Labels: enhancement 💎

#57 TransitionAnimation component
  package-lock.json
  package.json
  src/__snapshots__/index.test.ts.snap
  src/components/TransitionAnimation/TransitionAnimation.story.tsx
  src/components/TransitionAnimation/TransitionAnimation.style.tsx
  src/components/TransitionAnimation/TransitionAnimation.template.tsx
  src/components/TransitionAnimation/TransitionAnimation.test.tsx
  src/components/TransitionAnimation/__snapshots__/TransitionAnimation.test.tsx.snap
  src/components/TransitionAnimation/animations/fade.ts
  src/components/TransitionAnimation/animations/zoom.ts
  src/components/TransitionAnimation/index.ts
  src/themes/MosTheme/MosTheme.theme.ts
Labels: new addition 👶

#69 Changed Secondary Button color
  src/__snapshots__/index.test.ts.snap
  src/themes/MosTheme/MosTheme.theme.ts
Labels: bugfix 🕶
