Repository MyOnlineStore/bricks, pull requests merged in 2018-04, with the labels that each got.

#13 Added BreakpointProvider
  config/storybook/addons.js
  config/storybook/config.js
  config/typescript/tslint.json
  package-lock.json
  package.json
  src/__snapshots__/index.test.ts.snap
  src/components/BreakpointProvider/BreakpointProvider.story.tsx
  src/components/BreakpointProvider/BreakpointProvider.template.tsx
  src/components/BreakpointProvider/BreakpointProvider.test.tsx
  src/components/BreakpointProvider/index.tsx
  src/declarations/modules.d.ts
  src/index.test.ts
Labels: new addition

#15 FoldOut component
  config/jest/jest.config.json
  config/storybook/decorators/themeDecorator.tsx
  config/typescript/tslint.json
  package-lock.json
  package.json
  src/__snapshots__/index.test.ts.snap
  src/components/Button/Button.style.tsx
  src/components/FoldOut/FoldOut.story.tsx
  src/components/FoldOut/FoldOut.style.tsx
  src/components/FoldOut/FoldOut.template.tsx
  src/components/FoldOut/FoldOut.test.tsx
  src/components/FoldOut/index.ts
  src/components/Icon/Icon.style.tsx
  src/components/Spacer/Spacer.template.tsx
  src/index.test.ts
  src/utility/styled/index.ts
Labels: new addition

#17 Added Text Components
  .travis.yml
  config/storybook/addons.js
  config/storybook/config.js
  package-lock.json
  package.json
  src/__snapshots__/index.test.ts.snap
  src/components/BreakpointProvider/index.ts
  src/components/Heading/Heading.story.tsx
  src/components/Heading/Heading.style.tsx
  src/components/Heading/Heading.template.tsx
  src/components/Heading/index.ts
  src/components/SubHeading/SubHeading.story.tsx
  src/components/SubHeading/SubHeading.style.tsx
  src/components/SubHeading/index.ts
  src/components/Text/Text.story.tsx
  src/components/Text/Text.style.tsx
  src/components/Text/Text.template.tsx
  src/components/Text/index.ts
  src/index.ts
  src/themes.ts
Labels: new addition

#19 Add PR template
  PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#18 Added FlatButton component, adjusted themeType
  package.json
  src/__snapshots__/index.test.ts.snap
  src/components/Button/Button.style.tsx
  src/components/Button/Button.template.tsx
  src/components/FlatButton/FlatButton.story.tsx
  src/components/FlatButton/FlatButton.style.tsx
  src/components/FlatButton/index.ts
  src/themes.ts
Labels: new addition

#21 Added MOSTheme provider, moved types
  config/storybook/decorators/themeDecorator.tsx
  package-lock.json
  package.json
  src/__snapshots__/index.test.ts.snap
  src/components/Button/Button.style.tsx
  src/components/FlatButton/FlatButton.style.tsx
  src/components/Icon/Icon.template.tsx
  src/components/Spacer/Spacer.style.tsx
  src/index.ts
  src/themes/MosTheme/MosTheme.template.tsx
  src/themes/MosTheme/MosTheme.theme.ts
  src/themes/MosTheme/index.ts
  src/themes/types/ButtonThemeType.ts
  src/themes/types/ThemeType.ts
  src/utility/styled/index.ts
Labels: new addition

#23 Fixed Icon interpolation bug
  src/components/Icon/Icon.style.tsx
  src/index.ts
Labels: bug 💩

#28 Added Foldout resizing on inner resize
  package-lock.json
  package.json
  src/__snapshots__/index.test.ts.snap
  src/components/FoldOut/FoldOut.story.tsx
  src/components/FoldOut/FoldOut.style.tsx
  src/components/FoldOut/FoldOut.template.tsx
  src/components/FoldOut/FoldOut.test.tsx
  src/components/FoldOut/__snapshots__/FoldOut.test.tsx.snap
Labels: bugfix 🕶, enhancement 💎

#25 Added disabled state to Button
  src/__snapshots__/index.test.ts.snap
  src/components/Button/Button.story.tsx
  src/components/Button/Button.style.tsx
  src/components/Button/Button.template.tsx
  src/components/FlatButton/FlatButton.style.tsx
  src/components/FlatButton/FlatButton.template.tsx
  src/components/FlatButton/FlatButton.test.tsx
  src/themes/MosTheme/MosTheme.theme.ts
  src/themes/types/FlatButtonThemeType.ts
  src/themes/types/ThemeType.ts
Labels: enhancement 💎

#26 Added Notification
  config/typescript/tslint.json
  package-lock.json
  package.json
  src/__snapshots__/index.test.ts.snap
  src/components/BreakpointProvider/BreakpointProvider.story.tsx
  src/components/Button/Button.test.tsx
  src/components/FoldOut/FoldOut.story.tsx
  src/components/Icon/Icon.template.tsx
  src/components/Icon/index.ts
  src/components/Notification/Notification.story.tsx
  src/components/Notification/Notification.style.tsx
  src/components/Notification/Notification.template.tsx
  src/components/Notification/index.ts
  src/components/Spacer/Spacer.story.tsx
  src/index.ts
  src/themes/MosTheme/MosTheme.theme.ts
  src/themes/types/NotificationThemeType.ts
  src/themes/types/ThemeType.ts
Labels: new addition 👶

#32 Added circleci
  .circleci/config.yml
  .gitignore
  .travis.yml
  README.md
  package-lock.json
  package.json
Labels: enhancement 💎

#29 Added ErrorBoundary
  package.json
  src/__snapshots__/index.test.ts.snap
  src/components/ErrorBoundary/ErrorBoundary.story.tsx
  src/components/ErrorBoundary/ErrorBoundary.template.tsx
  src/components/ErrorBoundary/ErrorBoundary.test.tsx
  src/components/ErrorBoundary/__snapshots__/ErrorBoundary.test.tsx.snap
  src/components/ErrorBoundary/index.ts
  src/components/FlatButton/FlatButton.story.tsx
  src/components/FoldOut/FoldOut.story.tsx
  src/components/Heading/Heading.story.tsx
  src/components/Icon/Icon.story.tsx
  src/components/Notification/Notification.story.tsx
  src/components/Spacer/Spacer.story.tsx
  src/components/SubHeading/SubHeading.story.tsx
  src/components/Text/Text.story.tsx
Labels: new addition 👶

#35 Fixed disabled Button background transition
  src/__snapshots__/index.test.ts.snap
  src/components/Button/Button.style.tsx
Labels: bugfix 🕶

#36 Added PriceTag component
  src/__snapshots__/index.test.ts.snap
  src/components/PriceTag/PriceTag.story.tsx
  src/components/PriceTag/PriceTag.style.tsx
  src/components/PriceTag/PriceTag.template.tsx
  src/components/PriceTag/PriceTag.test.tsx
  src/components/PriceTag/__snapshots__/PriceTag.test.tsx.snap
  src/components/PriceTag/formatters/formatCurrency.ts
  src/components/PriceTag/formatters/formatDecimalSeperator.ts
  src/components/PriceTag/formatters/formatFraction.tsx
  src/components/PriceTag/index.ts
  src/themes/MosTheme/MosTheme.theme.ts
  src/themes/types/ThemeType.ts
Labels: new addition 👶

#38 Added pricetag to main index
  src/index.ts
Labels: enhancement 💎

#39 Added actionprice and free label
  package-lock.json
  package.json
  src/__snapshots__/index.test.ts.snap
  src/components/PriceTag/PriceTag.story.tsx
  src/components/PriceTag/PriceTag.style.tsx
  src/components/PriceTag/PriceTag.template.tsx
  src/components/PriceTag/PriceTag.test.tsx
  src/components/PriceTag/__snapshots__/PriceTag.test.tsx.snap
  src/themes/MosTheme/MosTheme.theme.ts
  src/themes/types/ThemeType.ts
Labels: enhancement 💎

#42 Added webpack prod config
  .circleci/config.yml
  config/webpack/webpack.config.js
  package-lock.json
  package.json
Labels: tooling 🤖
