Repository MyOnlineStore/bricks, pull requests merged in 2018-11, with the labels that each got.

#248 Added automatic deployments to now.sh for each push to the repo
  .dockerignore
  .gitignore
  Dockerfile
  now.json
  package.json
  src/utility/SubscriptionContext/index.tsx
Labels: tooling 🤖

#247 Textfield style bugs
  src/components/FormRow/__snapshots__/story.storyshot
  src/components/Range/__snapshots__/story.storyshot
  src/components/TextField/__snapshots__/story.storyshot
  src/components/TextField/index.tsx
  src/components/TextField/story.tsx
  src/components/TextField/style.tsx
  src/themes/MosTheme/MosTheme.theme.ts
Labels: bugfix 🕶

#258 Removed default offset from checkbox
  src/components/Checkbox/__snapshots__/story.storyshot
  src/components/Checkbox/index.tsx
  src/components/Checkbox/style.tsx
  src/components/FormRow/__snapshots__/story.storyshot
  src/components/FormRow/index.tsx
  src/components/FormRow/style.tsx
  src/components/InlineNotification/__snapshots__/story.storyshot
  src/components/Link/__snapshots__/story.storyshot
  src/components/MessageStream/__snapshots__/story.storyshot
  src/components/Modal/__snapshots__/story.storyshot
  src/components/MultiButton/__snapshots__/story.storyshot
  src/components/Popover/__snapshots__/story.storyshot
  src/components/PriceTag/__snapshots__/story.storyshot
  src/components/RadioButton/__snapshots__/story.storyshot
  src/components/RadioButtonGroup/__snapshots__/story.storyshot
  src/components/Raised/__snapshots__/story.storyshot
  src/components/Range/__snapshots__/story.storyshot
  src/components/ScrollBox/__snapshots__/story.storyshot
  src/components/Select/__snapshots__/story.storyshot
  src/components/Skeleton/__snapshots__/story.storyshot
  src/components/Spacer/__snapshots__/story.storyshot
  src/components/Table/__snapshots__/story.storyshot
  src/components/TextArea/__snapshots__/story.storyshot
  src/components/TextField/__snapshots__/story.storyshot
  src/components/Tile/__snapshots__/story.storyshot
  src/components/Toaster/__snapshots__/story.storyshot
  src/components/Toggle/__snapshots__/story.storyshot
  src/components/TransitionAnimation/__snapshots__/story.storyshot
Labels: bugfix 🕶

#236 Skeleton Rect
  package-lock.json
  package.json
  src/components/Skeleton/Rect/index.tsx
  src/components/Skeleton/Rect/style.tsx
  src/components/Skeleton/__snapshots__/story.storyshot
  src/components/Skeleton/index.tsx
  src/components/Skeleton/story.tsx
  src/components/Skeleton/style.tsx
  src/components/Skeleton/test.tsx
  src/components/Spacer/__snapshots__/story.storyshot
  src/components/Table/__snapshots__/story.storyshot
  src/components/TextArea/__snapshots__/story.storyshot
  src/components/Tile/__snapshots__/story.storyshot
  src/components/Toaster/__snapshots__/story.storyshot
  src/components/TransitionAnimation/__snapshots__/story.storyshot
Labels: new addition 👶

#257 removed onFocus- onBlurCapture from wrapper to prevent double focus
  src/components/FormRow/__snapshots__/story.storyshot
  src/components/Range/__snapshots__/story.storyshot
  src/components/TextField/__snapshots__/story.storyshot
  src/components/TextField/index.tsx
  src/components/TextField/test.tsx
Labels: bugfix 🕶

#251 Added rgba utility function
  package-lock.json
  package.json
  src/index.ts
  src/utility/rgba/index.ts
  src/utility/rgba/test.ts
Labels: enhancement 💎

#262 Added auto dismiss prop to Toaster
  src/components/Toaster/__snapshots__/story.storyshot
  src/components/Toaster/index.tsx
  src/components/Toaster/story.tsx
  src/components/Toaster/test.tsx
Labels: enhancement 💎

#265 Added Seperated component
  src/components/Box/__snapshots__/story.storyshot
  src/components/Box/style.tsx
  src/components/Box/test.tsx
  src/components/Button/__snapshots__/story.storyshot
  src/components/ButtonGroup/__snapshots__/story.storyshot
  src/components/Checkbox/__snapshots__/story.storyshot
  src/components/Contrast/__snapshots__/story.storyshot
  src/components/EmptyState/__snapshots__/story.storyshot
  src/components/ErrorBoundary/__snapshots__/test.tsx.snap
  src/components/FoldOut/__snapshots__/story.storyshot
  src/components/FormRow/__snapshots__/story.storyshot
  src/components/Icon/__snapshots__/story.storyshot
  src/components/InlineNotification/__snapshots__/story.storyshot
  src/components/MessageStream/__snapshots__/story.storyshot
  src/components/Modal/__snapshots__/story.storyshot
  src/components/MultiButton/__snapshots__/story.storyshot
  src/components/Notification/__snapshots__/story.storyshot
  src/components/Popover/__snapshots__/story.storyshot
  src/components/RadioButton/__snapshots__/story.storyshot
  src/components/RadioButtonGroup/__snapshots__/story.storyshot
  src/components/RadioButtonGroup/story.tsx
  src/components/Raised/__snapshots__/story.storyshot
  src/components/Range/__snapshots__/story.storyshot
  src/components/ScrollBox/__snapshots__/story.storyshot
  src/components/Select/Option/__snapshots__/test.tsx.snap
  src/components/Select/__snapshots__/story.storyshot
  src/components/Select/test.tsx
  src/components/Separated/__snapshots__/story.storyshot
  src/components/Separated/index.tsx
  src/components/Separated/story.tsx
  src/components/Separated/test.tsx
  src/components/Spacer/__snapshots__/story.storyshot
  src/components/Table/__snapshots__/story.storyshot
  src/components/TextArea/__snapshots__/story.storyshot
  src/components/TextField/__snapshots__/story.storyshot
  src/components/Tile/__snapshots__/story.storyshot
  src/components/Toaster/__snapshots__/story.storyshot
  src/components/Toggle/__snapshots__/story.storyshot
  src/components/TransitionAnimation/__snapshots__/story.storyshot
  src/index.ts
Labels: new addition 👶

#268 Removed z-index from RadioButton center
  src/components/FormRow/__snapshots__/story.storyshot
  src/components/RadioButton/__snapshots__/story.storyshot
  src/components/RadioButton/style.tsx
  src/components/RadioButtonGroup/__snapshots__/story.storyshot
Labels: bugfix 🕶

#266 Fixed TextField.Number to allow it to be empty
  package.json
  src/components/TextField/formatters/withNumberFormatting/index.tsx
  src/components/TextField/formatters/withNumberFormatting/test.tsx
Labels: bugfix 🕶
