Repository MyOnlineStore/bricks, pull requests merged in 2018-12, with the labels that each got.

#274 Fix for Now deploys
  Dockerfile
  package-lock.json
Labels: bugfix 🕶

#273 Removed checkbox class
  src/components/Checkbox/__snapshots__/story.storyshot
  src/components/Checkbox/index.tsx
  src/components/FormRow/__snapshots__/story.storyshot
  src/components/FormRow/index.tsx
  src/components/FormRow/story.tsx
  src/components/FormRow/style.tsx
Labels: breaking 🔥, bugfix 🕶

#275 Added disableNegative prop to CurrencyFormatter
  src/components/TextField/formatters/withCurrencyFormatting/index.tsx
  src/components/TextField/formatters/withCurrencyFormatting/test.tsx
  src/components/TextField/story.tsx
Labels: enhancement 💎

#277 Created spinner component
  src/components/Separated/__snapshots__/story.storyshot
  src/components/Spacer/__snapshots__/story.storyshot
  src/components/Spinner/__snapshots__/story.storyshot
  src/components/Spinner/index.tsx
  src/components/Spinner/story.tsx
  src/components/Spinner/style.tsx
  src/components/Table/__snapshots__/story.storyshot
  src/components/TextArea/__snapshots__/story.storyshot
  src/components/Tile/__snapshots__/story.storyshot
  src/components/Toaster/__snapshots__/story.storyshot
  src/components/TransitionAnimation/__snapshots__/story.storyshot
  src/index.ts
Labels: new addition 👶

#284 Changed pr template to better identify semver
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation 📝

#282 Select handles change events
  src/components/Select/__snapshots__/story.storyshot
  src/components/Select/index.tsx
  src/components/Select/test.tsx
Labels: enhancement 💎

#279 Created loading state for Button
  src/components/Button/__snapshots__/story.storyshot
  src/components/Button/index.tsx
  src/components/Button/story.tsx
  src/components/Button/style.tsx
  src/components/Button/test.tsx
  src/components/ButtonGroup/__snapshots__/story.storyshot
  src/components/ButtonGroup/__snapshots__/test.tsx.snap
  src/components/Checkbox/__snapshots__/story.storyshot
  src/components/Contrast/__snapshots__/story.storyshot
  src/components/EmptyState/__snapshots__/story.storyshot
  src/components/FoldOut/__snapshots__/story.storyshot
  src/components/FormRow/__snapshots__/story.storyshot
  src/components/Heading/__snapshots__/story.storyshot
  src/components/InlineNotification/__snapshots__/story.storyshot
  src/components/Link/__snapshots__/story.storyshot
  src/components/MessageStream/__snapshots__/story.storyshot
  src/components/Modal/__snapshots__/story.storyshot
  src/components/MultiButton/__snapshots__/story.storyshot
  src/components/MultiButton/index.tsx
  src/components/MultiButton/test.tsx
  src/components/Notification/__snapshots__/story.storyshot
  src/components/Popover/__snapshots__/story.storyshot
  src/components/PriceTag/__snapshots__/story.storyshot
  src/components/RadioButton/__snapshots__/story.storyshot
  src/components/RadioButtonGroup/__snapshots__/story.storyshot
  src/components/Raised/__snapshots__/story.storyshot
  src/components/Range/__snapshots__/story.storyshot
  src/components/ScrollBox/__snapshots__/story.storyshot
  src/components/Select/__snapshots__/story.storyshot
  src/components/Skeleton/__snapshots__/story.storyshot
  src/components/Spacer/__snapshots__/story.storyshot
  src/components/Spinner/__snapshots__/story.storyshot
  src/components/Spinner/style.tsx
  src/components/Table/__snapshots__/story.storyshot
  src/components/TextField/__snapshots__/story.storyshot
  src/components/Tile/__snapshots__/story.storyshot
  src/components/Toaster/__snapshots__/story.storyshot
  src/components/Toggle/__snapshots__/story.storyshot
  src/components/TransitionAnimation/__snapshots__/story.storyshot
  src/themes/MosTheme/MosTheme.theme.ts
Labels: enhancement 💎

#285 Select no longer triggers a change when a value is entered
  src/components/Select/index.tsx
  src/components/Select/test.tsx
Labels: bugfix 🕶

#283 Removed storyshots
  package-lock.json
  package.json
  src/components/Badge/__snapshots__/story.storyshot
  src/components/Box/__snapshots__/story.storyshot
  src/components/Branch/__snapshots__/story.storyshot
  src/components/BreakpointProvider/__snapshots__/story.storyshot
  src/components/Button/__snapshots__/story.storyshot
  src/components/ButtonGroup/__snapshots__/story.storyshot
  src/components/Checkbox/__snapshots__/story.storyshot
  src/components/Contrast/__snapshots__/story.storyshot
  src/components/EmptyState/__snapshots__/story.storyshot
  src/components/ErrorBoundary/__snapshots__/story.storyshot
  src/components/FoldOut/__snapshots__/story.storyshot
  src/components/FormRow/__snapshots__/story.storyshot
  src/components/Heading/__snapshots__/story.storyshot
  src/components/Icon/__snapshots__/story.storyshot
  src/components/Illustration/__snapshots__/story.storyshot
  src/components/InlineNotification/__snapshots__/story.storyshot
  src/components/Link/__snapshots__/story.storyshot
  src/components/MessageStream/__snapshots__/story.storyshot
  src/components/Modal/__snapshots__/story.storyshot
  src/components/MultiButton/__snapshots__/story.storyshot
  src/components/Notification/__snapshots__/story.storyshot
  src/components/Popover/__snapshots__/story.storyshot
  src/components/PriceTag/__snapshots__/story.storyshot
  src/components/RadioButton/__snapshots__/story.storyshot
  src/components/RadioButtonGroup/__snapshots__/story.storyshot
  src/components/Raised/__snapshots__/story.storyshot
  src/components/Range/__snapshots__/story.storyshot
  src/components/ScrollBox/__snapshots__/story.storyshot
  src/components/Select/__snapshots__/story.storyshot
  src/components/Separated/__snapshots__/story.storyshot
  src/components/Skeleton/__snapshots__/story.storyshot
  src/components/Spacer/__snapshots__/story.storyshot
  src/components/Spinner/__snapshots__/story.storyshot
  src/components/Table/__snapshots__/story.storyshot
  src/components/Text/__snapshots__/story.storyshot
  src/components/TextArea/__snapshots__/story.storyshot
  src/components/TextField/__snapshots__/story.storyshot
  src/components/Tile/__snapshots__/story.storyshot
  src/components/Toaster/__snapshots__/story.storyshot
  src/components/Toggle/__snapshots__/story.storyshot
  src/components/TransitionAnimation/__snapshots__/story.storyshot
  src/index.test.ts
Labels: enhancement 💎

#287 Textfield.Currency supports minor units
  src/components/TextField/formatters/withCurrencyFormatting/index.tsx
  src/components/TextField/formatters/withCurrencyFormatting/test.tsx
  src/components/TextField/story.tsx
Labels: enhancement 💎

#289 Added shorthand tuple to Box
  src/components/Box/index.tsx
  src/components/Box/story.tsx
  src/components/Box/style.tsx
  src/components/Box/test.tsx
  src/types/OffsetType.ts
  src/utility/trbl/index.ts
Labels: enhancement 💎

#288 Improved modal responsiveness
  src/components/ButtonGroup/index.tsx
  src/components/Modal/index.tsx
  src/components/Modal/story.tsx
  src/components/Modal/style.tsx
  src/components/Modal/test.tsx
Labels: enhancement 💎
