Repository MyOnlineStore/bricks, pull requests merged in 2019-03, with the labels that each got.

#342 Added test-id to multiple components
  src/components/Badge/index.tsx
  src/components/Badge/test.tsx
  src/components/Box/test.tsx
  src/components/Breadcrumbs/index.tsx
  src/components/Breadcrumbs/test.tsx
  src/components/Button/base/index.tsx
  src/components/Button/index.tsx
  src/components/Button/test.tsx
  src/components/ButtonGroup/index.tsx
  src/components/ButtonGroup/test.tsx
  src/components/Checkbox/index.tsx
  src/components/Checkbox/test.tsx
  src/components/EmptyState/index.tsx
  src/components/EmptyState/test.tsx
  src/components/Link/index.tsx
  src/components/Link/test.tsx
  src/components/Modal/index.tsx
  src/components/Select/Option/index.tsx
  src/components/Select/index.tsx
  src/components/Select/story.tsx
  src/components/Select/test.tsx
Labels: enhancement 💎

#347 master merged into 1.x
  package-lock.json
  package.json
  src/components/Checkbox/index.tsx
  src/components/Checkbox/story.tsx
  src/components/FormRow/story.tsx
  src/components/Modal/index.tsx
  src/components/Range/style.tsx
  src/components/Table/Card/index.tsx
  src/components/Toast/style.tsx
  src/themes/MerchantTheme/MerchantTheme.template.tsx
  src/themes/MerchantTheme/index.ts
  src/themes/MerchantTheme/index.tsx
  src/types/OffsetType/index.ts
Labels: high priority ⚡️

#348 Fixed SSR
  package-lock.json
  webpack.config.js
Labels: bugfix 🕶

#349 SCS-470 : Range Slider value to whole numbers
  package-lock.json
  package.json
  src/components/Range/index.tsx
  src/components/Range/story.tsx
  src/components/Range/test.tsx
Labels: bugfix 🕶

#346 Removed BreakpointProvider
  __mocks__/react-measure.tsx
  package-lock.json
  package.json
  src/components/BreakpointProvider/index.tsx
  src/components/BreakpointProvider/story.tsx
  src/components/BreakpointProvider/test.tsx
  src/components/ButtonGroup/test.tsx
  src/components/FoldOut/index.tsx
  src/components/FoldOut/test.tsx
  src/components/Modal/index.tsx
  src/components/Modal/test.tsx
  src/components/Table/story.tsx
  src/components/Toast/index.tsx
Labels: enhancement 💎

#341 Hover fix responsive tables
  src/components/Table/Card/index.tsx
  src/components/Table/Card/test.tsx
  src/components/Table/Row/style.tsx
Labels: bugfix 🕶

#352 Bundlesize
  .circleci/config.yml
  package-lock.json
  package.json
Labels: tooling 🤖

#355 Component theme fixes for 1.x
  src/components/Checkbox/style.tsx
  src/components/Link/style.tsx
  src/components/RadioButton/style.tsx
  src/components/TextArea/style.tsx
  src/components/TextField/style.tsx
  src/themes/MosTheme/MosTheme.theme.ts
Labels: bugfix 🕶

#356 Update react(-dom) versions to be able to use Hooks
  package-lock.json
  package.json
  src/components/Checkbox/index.tsx
Labels: enhancement 💎

#357 Added focus border and boxshadow for textarea and textfield
  src/components/TextArea/index.tsx
  src/components/TextArea/style.tsx
  src/components/TextField/index.tsx
  src/components/TextField/style.tsx
  src/themes/MosTheme/MosTheme.theme.ts
Labels: bugfix 🕶
