Repository MyOnlineStore/bricks, pull requests merged in 2019-07, with the labels that each got.

#402 STRF : new icons to be used in storefronts
  src/assets/icons/block-background-color.svg
  src/assets/icons/block-hide-show-elements.svg
  src/assets/icons/menu-palet.svg
  src/assets/icons/menu-pencil.svg
  src/assets/icons/row-alignment.svg
  src/assets/icons/row-background.svg
  src/assets/icons/row-delete.svg
  src/assets/icons/row-duplicate.svg
  src/assets/icons/row-edit.svg
  src/assets/icons/settings-image.svg
  src/assets/icons/settings-link.svg
  src/assets/icons/settings-video.svg
Labels: enhancement 💎, work in progress ⚔

#400 Select fix scroll
  src/components/Select/index.tsx
  src/components/Select/story.tsx
  src/components/Select/style.tsx
  src/components/Select/test.tsx
  src/components/Table/test.tsx
Labels: bugfix 🕶

#404 Additional Slider props
  src/components/Slider/index.tsx
  src/components/Slider/story.tsx
  src/components/Slider/test.tsx
Labels: enhancement 💎

#406 Added documentation checkbox
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement 💎

#407 Popover documentation
  src/components/Popover/index.tsx
Labels: documentation 📝

#408 Added baseline for docs website
  .gitignore
  docs/components/Head.tsx
  docs/components/Nav.tsx
  docs/components/Page.tsx
  docs/next-env.d.ts
  docs/package.json
  docs/pages/_app.tsx
  docs/pages/index.tsx
  docs/static/fonts/melbourne-bold.eot
  docs/static/fonts/melbourne-bold.ttf
  docs/static/fonts/melbourne-light.eot
  docs/static/fonts/melbourne-light.ttf
  docs/static/fonts/melbourne.eot
  docs/static/fonts/melbourne.ttf
  docs/tsconfig.json
  docs/yarn.lock
Labels: documentation 📝

#410 GRWTH-736 MosCorporateTheme
  src/components/_MosCorporateTheme/story.tsx
  src/index.ts
  src/themes/MosCorporateTheme/index.tsx
  src/themes/MosCorporateTheme/theme.ts
Labels: new addition 👶

#411 Added support for ISO-15897 locales to pricetag
  src/components/PriceTag/index.tsx
  src/components/PriceTag/test.tsx
Labels: enhancement 💎

#414 Revert "Select fix scroll"
  src/components/Select/index.tsx
  src/components/Select/story.tsx
  src/components/Select/style.tsx
  src/components/Select/test.tsx
  src/components/Table/test.tsx
Labels: bugfix 🕶

#413 Added doc generation to docs website
  CONTRIBUTING.md
  docs/README.md
  docs/components/Page.tsx
  docs/lib/componentMap.tsx
  docs/next-env.d.ts
  docs/next.config.js
  docs/package.json
  docs/pages/_app.tsx
  docs/pages/components.tsx
  docs/pages/index.tsx
  docs/yarn.lock
  package.json
  scripts/copy-readme.js
  src/components/Badge/readme.mdx
Labels: documentation 📝

#415 Added implementation from TextualButton
  src/components/Button/base/index.tsx
  src/components/Button/base/style.tsx
  src/components/Button/base/test.tsx
  src/components/Button/index.tsx
  src/components/Button/story.tsx
  src/components/Button/test.tsx
  src/components/ButtonGroup/story.tsx
  src/components/IconButton/story.tsx
  src/components/Link/story.tsx
  src/components/MultiButton/story.tsx
  src/components/TextualButton/index.tsx
  src/components/TextualButton/story.tsx
  src/components/TextualButton/test.tsx
  src/components/_MerchantTheme/sampleContent.tsx
  src/index.ts
  src/themes/ExperimentalCustomTheme/genTheme.ts
  src/themes/MosTheme/MosTheme.theme.ts
  src/types/ThemeType/index.ts
Labels: new addition 👶

#418 Textfield is now testable with a data-testid
  src/components/TextField/formatters/withCurrencyFormatting/test.tsx
  src/components/TextField/formatters/withNumberFormatting/test.tsx
  src/components/TextField/index.tsx
  src/components/TextField/test.tsx
Labels: enhancement 💎

#416 TextualButton no longer renders double testid's
  src/components/Button/base/test.tsx
  src/components/Button/test.tsx
  src/components/IconButton/index.tsx
  src/components/TextualButton/index.tsx
  src/components/TextualButton/test.tsx
Labels: bugfix 🕶
