Repository MyOnlineStore/bricks, pull requests merged in 2019-12, with the labels that each got.

#469 Added Tooltip component
  src/components/Tooltip/index.tsx
  src/components/Tooltip/story.tsx
  src/components/Tooltip/style.tsx
  src/components/Tooltip/test.tsx
  src/index.ts
  src/themes/ExperimentalCustomTheme/genTheme.ts
  src/themes/MosTheme/MosTheme.theme.ts
  src/types/ThemeType/index.ts
Labels: new addition 👶

#470 Added character limit to TextArea
  src/components/TextArea/index.tsx
  src/components/TextArea/story.tsx
  src/components/TextArea/test.tsx
Labels: enhancement 💎

#472 Added TooltipWindow z-index
  src/components/Tooltip/index.tsx
  src/components/Tooltip/style.tsx
Labels: bugfix 🕶

#471 Added onMouseEnter and onMouseLeave to ButtonBase
  src/components/Button/base/index.tsx
Labels: bugfix 🕶

#473 Added testid to TextArea and adjusted padding and color
  src/components/TextArea/index.tsx
  src/components/TextArea/style.tsx
  src/themes/MosTheme/MosTheme.theme.ts
Labels: enhancement 💎

#474 Replaced copy icon
  src/assets/icons/copy.svg
Labels: enhancement 💎

#475 Adjusted deploy-storybook job
  .circleci/config.yml
Labels: tooling 🤖

#476 Changed Circle CI github token env variable
  .circleci/config.yml
Labels: tooling 🤖

#477 Removed CircleCI deploy step and added test to deploy action
  .circleci/config.yml
  .github/workflows/deploy.yml
Labels: tooling 🤖

#479 Moved token in deploy action
  .github/workflows/deploy.yml
Labels: tooling 🤖

#478 Added minor prop to PriceTag to handle minor units
  src/components/PriceTag/index.tsx
  src/components/PriceTag/story.tsx
  src/components/PriceTag/test.tsx
Labels: enhancement 💎

#482 Added new colors and replaced old colors
  .storybook/config.js
  src/components/Badge/test.tsx
  src/components/Spinner/story.tsx
  src/index.ts
  src/themes/MosCorporateTheme/theme.ts
  src/themes/MosTheme/MosTheme.theme.ts
  src/themes/MosTheme/colors.ts
  src/themes/MosTheme/index.ts
Labels: enhancement 💎

#485 Added float support to TextField.Number
  src/components/TextField/formatters/withNumberFormatting/index.tsx
  src/components/TextField/formatters/withNumberFormatting/test.tsx
  src/components/TextField/index.tsx
  src/components/TextField/story.tsx
Labels: enhancement 💎
