Repository MyOnlineStore/bricks, pull requests merged in 2019-01, with the labels that each got.

#297 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation 📝

#298 Added a horizontal rendering for EmptyState
  config/typescript/tslint.json
  src/components/EmptyState/index.tsx
  src/components/EmptyState/story.tsx
  src/components/EmptyState/test.tsx
  src/components/Heading/index.tsx
  src/components/Illustration/assets/balloon.color.svg
  src/components/Illustration/style.tsx
  src/components/Illustration/types.ts
Labels: enhancement 💎

#299 Resolved minor discrepancies
  src/components/Modal/index.tsx
  src/components/Modal/test.tsx
  src/themes/MosTheme/MosTheme.theme.ts
Labels: bugfix 🕶

#301 Master merged back into 1.x
  .github/PULL_REQUEST_TEMPLATE.md
  config/typescript/tslint.json
  package-lock.json
  package.json
  src/components/EmptyState/index.tsx
  src/components/EmptyState/story.tsx
  src/components/EmptyState/test.tsx
  src/components/Heading/index.tsx
  src/components/Illustration/assets/balloon.color.svg
  src/components/Illustration/style.tsx
  src/components/Illustration/types.ts
  src/components/Link/style.tsx
  src/components/Modal/index.tsx
  src/components/Modal/test.tsx
  src/components/Select/Option/__snapshots__/test.tsx.snap
  src/components/Select/Option/test.tsx
  src/components/Toaster/index.tsx
  src/components/Toaster/style.tsx
  src/themes/MosTheme/MosTheme.theme.ts
Labels: enhancement 💎, high priority ⚡️

#286 Storybook/webpack/babel upgrade
  .dockerignore
  Dockerfile
  config/storybook/.babelrc
  config/storybook/config.js
  config/storybook/webpack.config.js
  config/typescript/tsconfig.json
  config/webpack/webpack.config.js
  now.json
  package-lock.json
  package.json
  src/components/Badge/story.tsx
  src/components/Box/story.tsx
  src/components/Branch/story.tsx
  src/components/BreakpointProvider/story.tsx
  src/components/Button/story.tsx
  src/components/Checkbox/story.tsx
  src/components/EmptyState/story.tsx
  src/components/ErrorBoundary/story.tsx
  src/components/Heading/story.tsx
  src/components/InlineNotification/story.tsx
  src/components/Link/story.tsx
  src/components/Modal/story.tsx
  src/components/Popover/__snapshots__/test.tsx.snap
  src/components/Popover/story.tsx
  src/components/Popover/test.tsx
  src/components/PriceTag/story.tsx
  src/components/RadioButton/story.tsx
  src/components/Raised/story.tsx
  src/components/Range/story.tsx
  src/components/ScrollBox/story.tsx
  src/components/Select/story.tsx
  src/components/Table/story.tsx
  src/components/Text/story.tsx
  src/components/TextArea/story.tsx
  src/components/TextField/story.tsx
  src/components/Toaster/story.tsx
  src/components/Toggle/story.tsx
  src/components/TransitionAnimation/story.tsx
  src/declarations/modules.d.ts
Labels: tooling 🤖

#302 Created breadcrumbs component
  src/components/Breadcrumbs/index.tsx
  src/components/Breadcrumbs/story.tsx
  src/components/Breadcrumbs/style.tsx
  src/components/Breadcrumbs/test.tsx
  src/index.ts
  src/themes/MosTheme/MosTheme.theme.ts
  src/types/ThemeType.ts
Labels: new addition 👶

#303 Added multiple addons to storybook
  config/storybook/addons.js
  config/storybook/config.js
  config/storybook/public/favicon.ico
  package-lock.json
  package.json
  src/themes/MosTheme/MosTheme.theme.ts
Labels: tooling 🤖

#304 Fixed rendering of the button prop on EmptyState
  src/components/EmptyState/index.tsx
  src/components/EmptyState/test.tsx
Labels: bugfix 🕶

#308 Fixed Select padding
  src/components/Select/Option/__snapshots__/test.tsx.snap
  src/components/Select/Option/index.tsx
  src/components/Select/Option/test.tsx
  src/components/Select/index.tsx
Labels: bugfix 🕶, requires design review :art:

#294 Split buttons and fixed button spinner
  index.d.ts
  src/components/Button/BareButton/index.tsx
  src/components/Button/base/index.tsx
  src/components/Button/base/style.tsx
  src/components/Button/index.tsx
  src/components/Button/story.tsx
  src/components/Button/style.tsx
  src/components/Button/styleCta.tsx
  src/components/Button/styleDefault.tsx
  src/components/Button/styleFlat.tsx
  src/components/Button/test.tsx
  src/components/ButtonGroup/__snapshots__/test.tsx.snap
  src/components/IconButton/index.tsx
  src/components/IconButton/story.tsx
  src/components/Modal/index.tsx
  src/components/Modal/test.tsx
  src/components/Select/index.tsx
  src/components/Spinner/index.tsx
  src/components/Spinner/style.tsx
  src/components/Table/story.tsx
  src/components/Toaster/index.tsx
  src/components/Toaster/test.tsx
  src/themes/MosTheme/MosTheme.theme.ts
  src/types/OffsetType/index.ts
  src/types/ThemeType.ts
  src/types/ThemeType/index.ts
  themes/MerchantTheme/MerchantTheme.template.d.ts
  themes/MerchantTheme/index.d.ts
  themes/MosTheme/MosTheme.template.d.ts
  themes/MosTheme/MosTheme.theme.d.ts
  themes/MosTheme/index.d.ts
  types/OffsetType.d.ts
  types/ThemeType.d.ts
  types/ThemeType/index.d.ts
  types/_RecursivePartialType/index.d.ts
  types/_SeverityType/index.d.ts
  utility/_calculateRandomPercentage/index.d.ts
  utility/_styled/index.d.ts
  utility/rgba/index.d.ts
  utility/trbl/index.d.ts
Labels: enhancement 💎

#306 A little houskeeping on configs
  .storybook/.babelrc
  .storybook/addons.js
  .storybook/config.js
  .storybook/decorators/themeDecorator.tsx
  .storybook/preview-head.html
  .storybook/public/favicon.ico
  .storybook/public/fonts/melbourne-bold.eot
  .storybook/public/fonts/melbourne-bold.ttf
  .storybook/public/fonts/melbourne-light.eot
  .storybook/public/fonts/melbourne-light.ttf
  .storybook/public/fonts/melbourne.eot
  .storybook/public/fonts/melbourne.ttf
  .storybook/webpack.config.js
  __mocks__/cssMock.js
  __mocks__/fileMock.js
  __mocks__/react-beautiful-dnd.tsx
  __mocks__/react-input-range.tsx
  __mocks__/react-popper.tsx
  __mocks__/resize-observer-polyfill.ts
  __mocks__/simplebar.ts
  __mocks__/simplebarCss.ts
  config/jest/jest.config.json
  config/prettier/.prettierrc
  config/storybook/decorators/themeDecorator.tsx
  jest.config.js
  jest.framework.tsx
  jest.setup.tsx
  package.json
  src/components/Badge/test.tsx
  src/components/Box/test.tsx
  src/components/Branch/test.tsx
  src/components/Button/test.tsx
  src/components/ButtonGroup/test.tsx
  src/components/Checkbox/test.tsx
  src/components/FoldOut/test.tsx
  src/components/Icon/test.tsx
  src/components/PriceTag/test.tsx
  src/components/RadioButton/test.tsx
  src/components/Raised/test.tsx
  src/components/ScrollBox/test.tsx
  src/components/Select/test.tsx
  src/components/Separated/test.tsx
  src/components/Table/Row/test.tsx
  src/components/Text/test.tsx
  src/components/Toggle/test.tsx
  src/components/TransitionAnimation/test.tsx
  src/themes/MerchantTheme/MerchantTheme.test.tsx
  tsconfig.json
  tslint.json
  webpack.config.js
Labels: tooling 🤖

#317 Toaster manager
  .gitignore
  src/components/Badge/index.tsx
  src/components/Toast/index.tsx
  src/components/Toast/story.tsx
  src/components/Toast/style.tsx
  src/components/Toast/test.tsx
  src/components/Toaster/index.tsx
  src/components/Toaster/story.tsx
  src/components/Toaster/test.tsx
  src/components/TransitionAnimation/index.tsx
  src/index.ts
  src/types/ThemeType.ts
Labels: new addition 👶

#322 Removed light font weight
  src/components/Breadcrumbs/index.tsx
  src/components/Heading/index.tsx
  src/components/Heading/story.tsx
  src/components/Heading/test.tsx
  src/components/Text/story.tsx
  src/themes/MosTheme/MosTheme.theme.ts
Labels: enhancement 💎, requires design review :art:

#320 Added code conventions documentation
  CONTRIBUTING.md
  README.md
Labels: documentation 📝

#324 Added min-width to fix rendering issue in firefox
  src/components/TextField/style.tsx
Labels: bugfix 🕶

#326 Added no-unused flag to typscript
  src/components/Popover/test.tsx
  src/components/RadioButton/style.tsx
  src/components/ScrollBox/test.tsx
  src/components/TextField/formatters/withNumberFormatting/index.tsx
  src/components/TextField/story.tsx
  src/utility/rgba/index.ts
  tsconfig.json
  tslint.json
Labels: tooling 🤖
