Repository MyOnlineStore/bricks, pull requests merged in 2019-06, with the labels that each got.

#358 Theme Engine
  package.json
  src/components/Badge/index.tsx
  src/components/Breadcrumbs/style.tsx
  src/components/Button/index.tsx
  src/components/Checkbox/style.tsx
  src/components/Contrast/style.tsx
  src/components/Heading/index.tsx
  src/components/IconButton/index.tsx
  src/components/IconButton/story.tsx
  src/components/Illustration/style.tsx
  src/components/Link/style.tsx
  src/components/MessageStream/style.tsx
  src/components/Modal/style.tsx
  src/components/MultiButton/style.tsx
  src/components/Notification/style.tsx
  src/components/Popover/style.tsx
  src/components/PriceTag/style.tsx
  src/components/RadioButton/style.tsx
  src/components/Raised/index.tsx
  src/components/Range/style.tsx
  src/components/ScrollBox/style.tsx
  src/components/Select/style.tsx
  src/components/Skeleton/style.tsx
  src/components/Table/style.tsx
  src/components/Text/index.tsx
  src/components/TextArea/style.tsx
  src/components/TextField/style.tsx
  src/components/Tile/index.tsx
  src/components/Toast/style.tsx
  src/components/Toggle/style.tsx
  src/components/_MerchantTheme/sampleContent.tsx
  src/components/_MerchantTheme/story.tsx
  src/index.ts
  src/themes/ExperimentalCustomTheme/MerchantThemeTypes.ts
  src/themes/ExperimentalCustomTheme/ThemeTools.ts
  src/themes/ExperimentalCustomTheme/genTheme.ts
  src/themes/ExperimentalCustomTheme/index.tsx
  yarn.lock
Labels: enhancement 💎

#389 added gentheme to index.ts exports
  src/index.ts
Labels: bugfix 🕶

#393 Added new text formatting icons
  src/assets/icons/format-fontsize-large.svg
  src/assets/icons/format-fontsize-medium.svg
  src/assets/icons/format-fontsize-small.svg
  src/assets/icons/format-letter-case.svg
  src/assets/icons/format-letter-lowercase.svg
  src/assets/icons/format-letter-uppercase.svg
  src/assets/icons/format-underline.svg
  src/assets/index.ts
Labels: enhancement 💎

#394 Added correct icon names
  src/assets/icons/format-fontsize-l.svg
  src/assets/icons/format-fontsize-m.svg
  src/assets/icons/format-fontsize-s.svg
  src/assets/index.ts
Labels: bugfix 🕶

#397 Reinstate MerchantTheme
  src/index.ts
  src/themes/MerchantTheme/index.tsx
Labels: bugfix 🕶

#396 GRWTH-624 Use Measure client instead of bounds
  src/components/FoldOut/index.tsx
  src/components/FoldOut/test.tsx
  src/components/Modal/index.tsx
  src/components/Modal/test.tsx
  src/components/Toast/index.tsx
Labels: bugfix 🕶

#388 Commit hooks
  .huskyrc
  package.json
  src/components/Link/index.tsx
  yarn.lock
Labels: tooling 🤖

#395 New icons improved
  src/assets/icons/format-fontsize-l.svg
  src/assets/icons/format-fontsize-m.svg
  src/assets/icons/format-fontsize-s.svg
  src/assets/icons/format-icons-bold.svg
  src/assets/icons/format-icons-italic.svg
  src/assets/icons/format-underline.svg
Labels: enhancement 💎

#387 passed click event to button components onClick callback
  src/components/Button/base/index.tsx
  src/components/Button/test.tsx
  src/components/Link/index.tsx
  src/components/Link/test.tsx
Labels: enhancement 💎
