Repository MyOnlineStore/bricks, pull requests merged in 2019-11, with the labels that each got.

#462 Added media prop to Modal
  .storybook/public/modal.svg
  src/assets/illustrations/yoga.svg
  src/components/Modal/index.tsx
  src/components/Modal/story.tsx
  src/components/Modal/test.tsx
Labels: enhancement 💎, requires design review :art:

#463 Modal centered
  src/components/Modal/index.tsx
  src/components/Modal/story.tsx
  src/components/Modal/test.tsx
Labels: enhancement 💎, requires design review :art:

#465 Adjusted CircleCI config
  .circleci/config.yml
Labels: tooling 🤖

#467 BIER-1308 : Implemented bleed and overlap props for modal media
  src/assets/illustrations/address.svg
  src/components/Modal/index.tsx
  src/components/Modal/story.tsx
Labels: enhancement 💎
