Repository MyOnlineStore/bricks, pull requests merged in 2019-05, with the labels that each got.

#370 Added badge to FormRow
  src/components/FormRow/index.tsx
  src/components/FormRow/story.tsx
Labels: enhancement 💎

#363 Updated ReadMe
  README.md
Labels: enhancement 💎

#377 Added storybook-to-ghpages to CI
  .circleci/config.yml
  package.json
Labels: tooling 🤖

#379 Added yarn and updated node image 🐈🧶
  .circleci/config.yml
  Dockerfile
  package-lock.json
  package.json
  src/components/Table/index.tsx
  src/components/Table/story.tsx
  tsconfig.json
  yarn.lock
Labels: tooling 🤖

#378 Upgrade storybook to v5
  .storybook/addons.js
  .storybook/config.js
  .storybook/public/logo_en_white.svg
  .storybook/webpack.config.js
  package.json
  src/components/IconButton/story.tsx
  tsconfig.json
  yarn.lock
Labels: tooling 🤖

#380 Removed window check
  src/components/Toaster/index.tsx
  src/components/Toaster/test.tsx
Labels: bugfix 🕶

#381 Add GitHub to CircleCI known_hosts
  .circleci/config.yml
Labels: tooling 🤖

#384 Added z-index to box
  src/components/Box/index.tsx
  src/components/Box/story.tsx
  src/components/Box/style.tsx
  src/components/Box/test.tsx
Labels: enhancement 💎

#383 Align RadioButton labels to center
  src/components/RadioButton/story.tsx
  src/components/RadioButton/style.tsx
Labels: bugfix 🕶

#385 New icons added
  src/assets/icons/format-icons-align-center.svg
  src/assets/icons/format-icons-align-left.svg
  src/assets/icons/format-icons-align-right.svg
  src/assets/icons/format-icons-background-color.svg
  src/assets/icons/format-icons-bold.svg
  src/assets/icons/format-icons-bullet.svg
  src/assets/icons/format-icons-italic.svg
  src/assets/icons/format-icons-link.svg
  src/assets/icons/format-icons-list-number.svg
  src/assets/icons/format-icons-vertical-center.svg
  src/assets/icons/format-icons-vertical-down.svg
  src/assets/icons/format-icons-vertical-top.svg
  src/assets/index.ts
Labels: enhancement 💎

#386 Moved ; into style rules for box
  src/components/Box/style.tsx
Labels: bugfix 🕶
