Repository MyOnlineStore/bricks, pull requests merged in 2019-08, with the labels that each got.

#417 Added readme-template for components
  README_TEMPLATE.mdx
  docs/.babelrc
  docs/package.json
  docs/pages/_document.tsx
  docs/yarn.lock
  src/components/Badge/readme.mdx
Labels: documentation 📝

#420 Disable 'max-file-line-count' in tslint and remove all references
  src/components/Select/test.tsx
  src/components/Table/test.tsx
  src/themes/MosCorporateTheme/theme.ts
  src/themes/MosTheme/MosTheme.theme.ts
  tslint.json
Labels: tooling 🤖

#419 Correctly render Skeletons in a FormRow
  src/components/FormRow/index.tsx
  src/components/FormRow/story.tsx
Labels: bugfix 🕶

#421 Disable TSLint no-unbound-method
  src/components/Table/Card/index.tsx
  src/components/Table/Cell/index.tsx
  src/components/Table/Row/index.tsx
  tslint.json
Labels: tooling 🤖

#422 Add optional secondary button and persistent option to Toast
  src/components/Toast/index.tsx
  src/components/Toast/story.tsx
  src/components/Toast/test.tsx
Labels: enhancement 💎

#426 Radio testid
  src/components/RadioButton/index.tsx
  src/components/RadioButton/test.tsx
  src/components/Text/test.tsx
Labels: enhancement 💎

#427 Fix buttongroup focus order
  src/components/ButtonGroup/index.tsx
  src/components/ButtonGroup/story.tsx
  src/components/ButtonGroup/test.tsx
Labels: bugfix 🕶

#430 Icon name docs
  src/assets/README.md
  src/assets/index.ts
Labels: documentation 📝

#432 Horizontal strikethrough styling for pricetag component
  src/components/PriceTag/style.tsx
  src/themes/MosTheme/MosTheme.theme.ts
Labels: enhancement 💎
