Repository MyOnlineStore/bricks, pull requests merged in 2020-06, with the labels that each got.

#560 feat(Card): Added new Card component
  .gitignore
  packages/components/src/components/Card/index.tsx
  packages/components/src/components/Card/story.tsx
  packages/components/src/components/Card/style.tsx
  packages/components/src/index.ts
  packages/components/src/themes/CustomTheme/genTheme.ts
  packages/components/src/themes/MosTheme/MosTheme.theme.ts
  packages/components/src/types/ThemeType/index.ts
Labels: new addition 👶

#562 fix(Accordion): Added flex grow property to root element
  packages/components/src/components/Accordion/index.tsx
Labels: bugfix 🕶

#563 feat(Toggle): Added data-testid prop
  packages/components/src/components/Toggle/index.tsx
  packages/components/src/components/Toggle/test.tsx
Labels: enhancement 💎

#565 fix(Accordion): Moved button area
  packages/components/src/components/Accordion/index.tsx
  packages/components/src/components/Accordion/style.tsx
  packages/components/src/components/Accordion/test.tsx
Labels: enhancement 💎

#564 fix(TextField): disabled TextField is now also readable in safari
  packages/components/src/components/TextArea/style.tsx
  packages/components/src/components/TextField/style.tsx
Labels: bugfix 🕶

#567 feat(bricks-assets): Added no-cookie icon
  packages/assets/src/icons/no-cookie.svg
Labels: new addition 👶

#568 fix(Accordion): Reset styles explicitly
  packages/components/src/components/Accordion/style.tsx
Labels: bugfix 🕶

#571 chore: Added commitlint
  .huskyrc
  .huskyrc.js
  commitlint.config.js
  package.json
  yarn.lock
Labels: tooling 🤖
