Repository MyOnlineStore/bricks, pull requests merged in 2020-03, with the labels that each got.

#509 Reintroduced sticky modal header
  package.json
  packages/assets/README.md
  packages/assets/package.json
  packages/components/package.json
  packages/components/src/components/Modal/index.tsx
  packages/components/src/components/Modal/story.tsx
  packages/components/src/types/OffsetType/index.ts
  rollup.config.js
  yarn.lock
Labels: enhancement 💎

#515 Add Component examples to Design System
  packages/components/docs/components/PreviewPane.tsx
  packages/components/docs/containers/examples/ButtonExamplesContainer.tsx
  packages/components/docs/containers/examples/badges/NumberBadgesExamples.tsx
  packages/components/docs/containers/examples/badges/SubscriptionBadgesExamples.tsx
  packages/components/docs/containers/examples/buttons/ButtonExamples.tsx
  packages/components/docs/containers/examples/buttons/ButtonGroupExamples.tsx
  packages/components/docs/containers/examples/buttons/CtaButtonExamples.tsx
  packages/components/docs/containers/examples/buttons/IconButtonExamples.tsx
  packages/components/docs/containers/examples/forms/CheckboxExamples.tsx
  packages/components/docs/containers/examples/forms/FormDescriptionsExamples.tsx
  packages/components/docs/containers/examples/forms/FormLabelsExamples.tsx
  packages/components/docs/containers/examples/forms/FormTipsExamples.tsx
  packages/components/docs/containers/examples/forms/RadiobuttonExamples.tsx
  packages/components/docs/containers/examples/forms/SelectExamples.tsx
  packages/components/docs/containers/examples/forms/SliderRangeExamples.tsx
  packages/components/docs/containers/examples/forms/StatefulTextField.tsx
  packages/components/docs/containers/examples/forms/TextFieldsExamples.tsx
  packages/components/docs/containers/examples/forms/ToggleExamples.tsx
  packages/components/docs/containers/examples/navigation/BreadcrumbsExamples.tsx
  packages/components/docs/containers/examples/overlays/DefaultModalExamples.tsx
  packages/components/docs/containers/examples/overlays/ModalWithIllustrationExamples.tsx
  packages/components/docs/containers/examples/overlays/PopoverExamples.tsx
  packages/components/docs/containers/examples/overlays/TooltipExamples.tsx
  packages/components/docs/containers/examples/search-sort/SortTableExamples.tsx
  packages/components/docs/containers/examples/status-indicators/InlineErrorExamples.tsx
  packages/components/docs/containers/examples/status-indicators/SkeletonExamples.tsx
  packages/components/docs/containers/examples/status-indicators/SpinnerExamples.tsx
  packages/components/docs/containers/examples/titles-text/BodyTextExamples.tsx
  packages/components/docs/containers/examples/titles-text/DisplayTextExamples.tsx
  packages/components/docs/containers/examples/titles-text/HeadingTextExamples.tsx
  packages/components/docs/containers/examples/titles-text/SubheadingTextExamples.tsx
  packages/components/docs/containers/examples/titles-text/TitleTextExamples.tsx
  packages/components/docs/markdown/components/badges.mdx
  packages/components/docs/markdown/components/buttons.mdx
  packages/components/docs/markdown/components/forms.mdx
  packages/components/docs/markdown/components/navigation.mdx
  packages/components/docs/markdown/components/overlays.mdx
  packages/components/docs/markdown/components/search.mdx
  packages/components/docs/markdown/components/status-indicators.mdx
  packages/components/docs/markdown/components/titles-text.mdx
  packages/components/docs/yarn.lock
  packages/components/src/components/Range/index.tsx
Labels: design system 🖼

#516 Move GlobalStyles from _document to _app
  packages/components/docs/pages/_app.tsx
  packages/components/docs/pages/_document.tsx
Labels: design system 🖼

#524 chore: add release task for publishing
  README.md
  lerna.json
  package.json
  packages/assets/package.json
  packages/components/package.json
Labels: tooling 🤖

#525 fix: Toggle margin
  packages/components/src/components/Toggle/index.tsx
Labels: 3

#528 feat(Toggle): removed unavailable prop
  packages/components/src/components/Toggle/index.tsx
  packages/components/src/components/Toggle/story.tsx
Labels: 3
