Repository MyOnlineStore/bricks, pull requests merged in 2020-04, with the labels that each got.

#532 fix(IconButton): explicit styling to prevent cascading properties
  packages/components/src/components/Button/base/style.tsx
  packages/components/src/components/IconButton/index.tsx
Labels: 3

#533 fix: Ensure correct placement with multiline labels
  packages/components/src/components/Checkbox/index.tsx
  packages/components/src/components/RadioButton/index.tsx
  packages/components/src/components/RadioButton/style.tsx
  packages/components/src/components/Toggle/index.tsx
Labels: 3

#534 fix(Button): Remove ::before
  packages/components/src/components/Button/index.tsx
Labels: 3

#538 fix: implement bricks 3 changes in design system site
  packages/components/docs/containers/examples/badges/CounterExamples.tsx
  packages/components/docs/containers/examples/badges/SubscriptionBadgesExamples.tsx
  packages/components/docs/lib/componentMap.tsx
  packages/components/docs/markdown/components/badges.mdx
  packages/components/docs/package.json
  packages/components/docs/pages/index.tsx
  packages/components/docs/yarn.lock
Labels: 3, design system 🖼

#539 fix(TextualButton): Prevent hover styles being overridden, change fontweight
  packages/components/src/components/TextualButton/index.tsx
  packages/components/src/themes/MosTheme/MosTheme.theme.ts
Labels: bugfix 🕶

#540 fix(Range, Slider): prevent overrides
  packages/components/src/components/Range/style.tsx
  packages/components/src/components/Slider/style.tsx
Labels: bugfix 🕶

#542 fix(Button): Make sure plain button border is rendered in chrome
  packages/components/src/components/Button/index.tsx
Labels: bugfix 🕶

#543 fix(InlineNotification): align to flex-start instead of to center
  packages/components/src/components/InlineNotification/index.tsx
Labels: bugfix 🕶

#545 docs: fix design system paragraph text variant
  packages/components/docs/lib/componentMap.tsx
Labels: bugfix 🕶, design system 🖼
