Repository MyOnlineStore/bricks, pull requests merged in 2020-07, with the labels that each got.

#576 feat(Select): Refactor Select into more split up components
  jest.framework.js
  package.json
  packages/components/env.d.ts
  packages/components/src/components/Select/SelectInput.tsx
  packages/components/src/components/Select/SelectList.tsx
  packages/components/src/components/Select/SelectModal.tsx
  packages/components/src/components/Select/SelectSearch.tsx
  packages/components/src/components/Select/SelectedOption.tsx
  packages/components/src/components/Select/index.tsx
  packages/components/src/components/Select/story.tsx
  packages/components/src/components/Select/style.tsx
  packages/components/src/components/Select/test.tsx
  tsconfig.json
  yarn.lock
Labels: bugfix 🕶

#582 feat(TextField): Feedback prop now supports a data-testid
  packages/components/src/components/InlineNotification/index.tsx
  packages/components/src/components/Text/index.tsx
  packages/components/src/components/TextField/index.tsx
  packages/components/src/components/TextField/test.tsx
Labels: enhancement 💎

#585 feat: Added CommentEmptyIcon
  packages/assets/src/icons/comment-empty.svg
Labels: new addition 👶
