Repository MyOnlineStore/bricks, pull requests merged in 2020-02, with the labels that each got.

#493 #455 - Remove deprecated stacked prop on ButtonGroup
  src/components/ButtonGroup/index.tsx
  src/components/ButtonGroup/test.tsx
Labels: enhancement 💎

#494 #433 - Use font colour for strikethrough PriceTag
  src/components/PriceTag/style.tsx
  src/components/PriceTag/test.tsx
  src/themes/ExperimentalCustomTheme/genTheme.ts
  src/themes/MosTheme/MosTheme.theme.ts
  src/types/ThemeType/index.ts
Labels: enhancement 💎

#492 #459 - Remove MerchantTheme
  README.md
  src/components/Badge/index.tsx
  src/components/Breadcrumbs/style.tsx
  src/components/Button/index.tsx
  src/components/Checkbox/style.tsx
  src/components/Contrast/style.tsx
  src/components/Heading/index.tsx
  src/components/IconButton/index.tsx
  src/components/Link/style.tsx
  src/components/MessageStream/style.tsx
  src/components/Modal/style.tsx
  src/components/MultiButton/style.tsx
  src/components/NativeSelect/style.tsx
  src/components/Notification/style.tsx
  src/components/Popover/style.tsx
  src/components/Progress/style.tsx
  src/components/RadioButton/style.tsx
  src/components/Raised/index.tsx
  src/components/Range/style.tsx
  src/components/ScrollBox/style.tsx
  src/components/Select/style.tsx
  src/components/Skeleton/style.tsx
  src/components/Slider/style.tsx
  src/components/Table/style.tsx
  src/components/Text/index.tsx
  src/components/TextArea/style.tsx
  src/components/TextField/style.tsx
  src/components/TextualButton/index.tsx
  src/components/Tile/index.tsx
  src/components/Toast/style.tsx
  src/components/Toggle/style.tsx
  src/components/Tooltip/style.tsx
  src/components/_CustomTheme/sampleContent.tsx
  src/components/_CustomTheme/story.tsx
  src/index.ts
  src/themes/CustomTheme/CustomThemeTypes.ts
  src/themes/CustomTheme/ThemeTools.ts
  src/themes/CustomTheme/genTheme.ts
  src/themes/CustomTheme/index.tsx
  src/themes/ExperimentalCustomTheme/index.tsx
Labels: enhancement 💎

#491 Refactored CurrencyField, props now properly apply
  src/components/TextField/formatters/CurrencyField/index.tsx
  src/components/TextField/formatters/CurrencyField/test.tsx
  src/components/TextField/formatters/withCurrencyFormatting/index.tsx
  src/components/TextField/formatters/withCurrencyFormatting/test.tsx
  src/components/TextField/formatters/withNumberFormatting/test.tsx
  src/components/TextField/index.tsx
  src/components/TextField/story.tsx
  src/components/TextField/test.tsx
Labels: bugfix 🕶

#499 Added explicit styling to IconButton states
  src/components/IconButton/index.tsx
Labels: bugfix 🕶

#498 Deploy design system site instead of storybook to GH pages
  .github/workflows/deploy.yml
  docs/CNAME
  docs/components/Head.tsx
  docs/lib/articles-to-pages.js
  docs/package.json
  docs/pages/index.tsx
  docs/yarn.lock
Labels: design system 🖼, tooling 🤖

#501 Design system: Add storybook link and fix side menu styling
  .gitignore
  docs/README.md
  docs/components/HeadingLink.tsx
  docs/components/Sidebar.tsx
  docs/components/SidebarLink.tsx
  docs/containers/Header.tsx
  docs/containers/SideNav.tsx
  docs/package.json
  docs/pages/generated/components/badges.tsx
  docs/pages/generated/components/buttons.tsx
  docs/pages/generated/components/forms.tsx
  docs/pages/generated/components/index.tsx
  docs/pages/generated/components/navigation.tsx
  docs/pages/generated/components/overlays.tsx
  docs/pages/generated/components/search.tsx
  docs/pages/generated/components/status-indicators.tsx
  docs/pages/generated/components/titles-text.tsx
  docs/pages/generated/design/colors.tsx
  docs/pages/generated/design/experience-values.tsx
  docs/pages/generated/design/icons.tsx
  docs/pages/generated/design/illustrations.tsx
  docs/pages/generated/design/index.tsx
  docs/pages/generated/design/layout.tsx
  docs/pages/generated/design/logo.tsx
  docs/pages/generated/design/typography.tsx
Labels: design system 🖼

#502 Update logo.mdx
  docs/markdown/design/logo.mdx
Labels: design system 🖼

#503 Add color board component
  docs/components/ColorBoard.tsx
  docs/markdown/design/colors.mdx
Labels: design system 🖼

#505 Fix now2 and GH pages deploys for 2.x
  .github/workflows/deploy.yml
  now.json
  package.json
  packages/components/package.json
  rollup.config.js
Labels: tooling 🤖

#506 Added correct types to svg components
  packages/assets/package.json
  packages/assets/scripts/types.js
Labels: bugfix 🕶

#510 Fix broken styling on plain Button variant
  packages/components/src/components/Button/index.tsx
Labels: bugfix 🕶

#512 Design System - Add PreviewPane component
  packages/components/docs/components/PreviewPane.tsx
  packages/components/docs/containers/examples/ButtonExamplesContainer.tsx
  packages/components/docs/markdown/components/buttons.mdx
  packages/components/docs/package.json
  packages/components/docs/yarn.lock
  packages/components/src/components/Contrast/index.tsx
Labels: design system 🖼, enhancement 💎

#514 Design System: Automatically link to first article in a category
  packages/components/docs/containers/Header.tsx
Labels: design system 🖼
